### ISSUE TITLE
Convert rollup-plugin to typescript

### ISSUE THREAD

**Issue by BethanyBerkowitz** [honeybadger-io/honeybadger-js#1010]
Our rollup plugin was written in Javascript, and may be a little bit of a pain to convert to Typescript. The code itself is easy to convert, but the testing setup was painful. 

See https://github.com/honeybadger-io/honeybadger-js/pull/1006#issuecomment-1410897881

**Comment by BethanyBerkowitz** [comment]
I remain curious about this problem, so I tried a few ideas: 

1. Write a custom loader that just combines the `testdouble` loader and `ts-node/esm` loader. Chaining loaders is available in node 18.6.0, but we want to be compatible back to node 14. Writing a loader was useful for learning about how loaders work, but ultimately I got some errors related to `quibble` not being set up correctly and it seemed like more trouble than it was worth, especially for a solution that's a bit hacky and undocumented. 
2. Transpile to JS first (`npx tsc -p tsconfig.test.json`, for example), then run mocha tests against the JS. This seems like it will work, and I think it would probably be fine to add a pretest step, even if it's not the standard way people usually do it. 

@subzero10 If you think adding a transpile step before testing is ok, I can go ahead with converting to TS. Or if you have any better ideas!

**Comment by subzero10** [comment]
Hey @BethanyBerkowitz,
I considered suggesting transpiling earlier, but the major drawback for me is the generated js files that we'd have to cleanup every time we finish testing (we don't want to commit those). Plus, testing with the IDE will require additional configuration but I guess that's OK.

Have you tried importing testdouble in your test files instead of using the loader?
```
import * as td from 'testdouble';
```

**Comment by BethanyBerkowitz** [comment]
> Hey @BethanyBerkowitz, I considered suggesting transpiling earlier, but the major drawback for me is the generated js files that we'd have to cleanup every time we finish testing (we don't want to commit those). Plus, testing with the IDE will require additional configuration but I guess that's OK.

If we put the generated files into a specific folder, we can gitignore them. But I agree that it's not an elegant solution!

>
> Have you tried importing testdouble in your test files instead of using the loader?
> 

Unfortunately in order to mock out imported esm modules, I need to use the loader. And I need to mock imported modules, otherwise our tests will make real API calls. Ultimately I think this comes down to the fact that Node made it sound like esm modules are fully operational and ready to go, so some tools like `node-fetch` went ahead and became esm-only, but actually the tooling is not very good yet 😬 

If I'd realized how annoying this would be, I would've just avoided node-fetch and the esm situation and used some other library!

**Comment by subzero10** [comment]
OK, thanks! I guess this leaves us with 2 options:
1. Go ahead with your suggestion to transpile first and then test against js.
2. Consider using a different combination of test frameworks and utilities. [Here's](https://www.xolv.io/blog/dev-notes/how-to-mock-with-testdouble-typescript-and-jest/) a document with instructions to setup testdouble, jest and typescript.

I prefer option 2, but then again I don't know how much effort it would be. It might be an overkill.

**Comment by BethanyBerkowitz** [comment]
> 2. Consider using a different combination of test frameworks and utilities. [Here's](https://www.xolv.io/blog/dev-notes/how-to-mock-with-testdouble-typescript-and-jest/) a document with instructions to setup testdouble, jest and typescript.
> 

I took a look at option 2 and I don't think it will work without converting to a non-esm module setup, which would require switching away from `node-fetch` v3. You can see in there that the examples are using `td.replace()`, which won't work with esm. To use esm, you need the testdouble loader and `td.replaceEsm()`. 

So the 2 options I see for adding typescript are 
1. Transpile for testing 
2. Switch away from node-fetch v3 (probably to node-fetch v2), get rid of the esm-only setup, and then use whatever test framework we want (jest if we want to standardize on that, or stick with mocha + testdouble). 

1 is a smaller change, but inelegant. 

2 is substantially bigger.. but the whole package is not that big so having to rewrite parts of it isn't a crazy idea to me. Another benefit of 2 would be that we wouldn't have to deal with these esm-only issues when pulling out the code to share with the webpack plugin. 

I gave a quick go at #2 today and found that I was able to get the code working with node-fetch v2. Didn't try testing it yet, but it seems promising.

**Comment by subzero10** [comment]
Gotcha! Let me know how it goes with moving away from an esm-only package.
