### ISSUE TITLE
Extract shared plugin code and share between rollup and webpack plugins

### ISSUE THREAD

**Issue by BethanyBerkowitz** [honeybadger-io/honeybadger-js#1013]
The rollup plugin was designed with code that can be shared with the webpack plugin. Extract the shared code and re-work both plugins so they share the core functionality (hbUtils.js and options.js in the rollup package). The only difference between the plugins should be how they hook into the build process and how they extract the necessary data from the bundle. 

Make sure that we do not lose any functionality from the webpack plugin in this process. Check carefully -- I thin we should be able to avoid breaking changes and a major version bump.

**Comment by BethanyBerkowitz** [comment]
ignorePaths is currently rollup only, ignoreErrors currently webpack only -- need to decide what to do about this

**Comment by BethanyBerkowitz** [comment]
Currently planning to move webpack plugin from adding options validation errors to the list of build errors in the compilation to just throwing an error if passed bad options. I think this this change is a positive one -- the user is only writing their code to set up the options once, so making an error with the options really obvious is positive. An error like forgetting to pass the apiKey is not going to be something intermittent, it's a total failure of setup, so I think it's correct that it would cause the build to fail completely. 

However, I'm not sure if this change could mean a major version update 😬

**Comment by subzero10** [comment]
> ignorePaths is currently rollup only, ignoreErrors currently webpack only -- need to decide what to do about this

What about both?

> Currently planning to move webpack plugin from adding options validation errors to the list of build errors in the compilation to just throwing an error if passed bad options. I think this this change is a positive one -- the user is only writing their code to set up the options once, so making an error with the options really obvious is positive. An error like forgetting to pass the apiKey is not going to be something intermittent, it's a total failure of setup, so I think it's correct that it would cause the build to fail completely.
> 
> However, I'm not sure if this change could mean a major version update 😬

I'm leaning towards a minor version update, and we could play it extra safe if we implement `ignoreErrors` to simply log warning messages even if validation fails. What do you think?

**Comment by BethanyBerkowitz** [comment]
> > ignorePaths is currently rollup only, ignoreErrors currently webpack only -- need to decide what to do about this
> 
> What about supporting both?
> 
https://github.com/honeybadger-io/honeybadger-js/issues/1210
https://github.com/honeybadger-io/honeybadger-js/issues/1209

> > Currently planning to move webpack plugin from adding options validation errors to the list of build errors in the compilation to just throwing an error if passed bad options. I think this this change is a positive one -- the user is only writing their code to set up the options once, so making an error with the options really obvious is positive. An error like forgetting to pass the apiKey is not going to be something intermittent, it's a total failure of setup, so I think it's correct that it would cause the build to fail completely.
> > However, I'm not sure if this change could mean a major version update 😬
> 
> I'm leaning towards a minor version update, and we could play it extra safe if we implement `ignoreErrors` to simply log warning messages even if validation fails. What do you think?

It turned out this was actually not an issue -- `plugin-core` will throw an error on a failed upload, but webpack will catch it and put it in the compilation error array. So I don't think this is a major version change 🥳
