### ISSUE TITLE
Duplicate JS errors reported in react-native on iOS, missing on Android

### ISSUE THREAD

**Issue by BethanyBerkowitz** [honeybadger-io/honeybadger-js#1054]
## What are the steps to reproduce this issue?
1. In `examples/react-native-cli`, run `npm install && cd ios && pod install && cd ..`
2. `npm start`
3. In another terminal, run a Release build of the example app `npx react-native run-ios --configuration Release`  (I did this on the simulator)
4. In the simulator (or on your device), enter your API key and click "Configure HB". 
5. Click "Throw a JS Error!"

## What happens?
In the HB UI, I see a duplicate error reported when throwing a JS error on iOS. 
<img width="1179" alt="Screen Shot 2023-04-04 at 10 28 44 AM" src="https://user-images.githubusercontent.com/16493493/229826501-c923759b-8c15-4cd3-b52e-783bedd0962b.png">

I was having this issue in my branch, but it turns out it happens on the released version of the package as well. 

One has the expected message: "This is a test error from the react-native-cli example project!"
- it does not have a stack trace 
- https://app.honeybadger.io/projects/108285/faults/94966597/01GX6B0YZBFDWRAF0JNZY0MME0?page=0 

Other one has prepended and appended data: "Unhandled JS Exception: Error: This is a test error from the react-native-cli example project!, js engine: hermes"
- does have a stack trace 
- https://app.honeybadger.io/projects/108285/faults/94966598/01GX6B0YZ89EST3BEK6G9JM6HN?page=0

## What were you expecting to happen?
Just one error, sent using the JS handler. 

## Any logs, error output, etc?
…

## Any other comments?
This is specific to production builds -- when running in dev mode (`npm run ios`), I only get one error with the expected `This is a test error from the react-native-cli example project!`. 

## What versions are you using?
**Operating System:** macOS Monterey, running xcode simulator for ios app
**Package Name:** react-native
**Package Version:** 5.1.6
**Browser Version:** n/a

**Comment by BethanyBerkowitz** [comment]
Ok, this is caused by https://github.com/honeybadger-io/honeybadger-js/blob/a10f68655e4949e32f0fbe0ed8cdb763232d6497/packages/react-native/index.js#L203-L206 -- removing the call to the previous error handler removes the duplicates. 

This doesn't necessarily mean we should just remove these lines -- maybe the built-in error handler is doing something important? But at least something here is not set up quite right.

**Comment by BethanyBerkowitz** [comment]
I've confirmed that when running in Release mode (`npx react-native run-ios --configuration Release`), a regular JS error does end up being handled by the native handler. 

In this example, I commented out the line where the JS handler is set up: https://github.com/honeybadger-io/honeybadger-js/blob/a10f68655e4949e32f0fbe0ed8cdb763232d6497/packages/react-native/index.js#L52 

I also added `onNativeIOSException` to the error class within `onNativeIOSException()`. The result was that I got 1 error reported, and it came through the native error handler. The decorators `Unhandled JS Exception` and `js engine: hermes` were added by the react-native error handler. 

<img width="1179" alt="Screen Shot 2023-04-07 at 10 27 39 AM" src="https://user-images.githubusercontent.com/16493493/230626545-2b815fcf-aa7d-474f-989b-82d1e1e98f90.png">

**Comment by BethanyBerkowitz** [comment]
On Android, I don't get any error reported at all when throwing the JS error in release mode (`npx react-native run-android --mode release`). I think this is related to #1050 -- the app crashes before anything is sent. I checked that I could send a simple `notify()`, so it's not a problem with the connection to the API. 

This does not improve if I remove the call to the previous JS handler -- I still don't get any error reported. The app freezes, so I think that supports the theory that even a JS error causes a fatal crash before the error is sent to HB.

**Comment by subzero10** [comment]
> When run in dev mode (npm run ios), I get no reported JS error at all without the JS handler -- it seems that react-native just shows the error in the UI and doesn't send it to its native error handler.

Are you saying that the JS handler is necessary only in dev mode? 🤔 
If that was the case, we could only attach it when the app is running in dev mode **and** honeybadger reporting is enabled.
However, I doubt this is the case, right? Maybe we get more information/context about the error when it gets reported with the JS handler?

> On Android, I don't get any error reported at all when throwing the JS error in release mode (`npx react-native run-android --mode release`). I think this is related to #1050 -- the app crashes before anything is sent. I checked that I could send a simple `notify()`, so it's not a problem with the connection to the API.
> 
> This does not improve if I remove the call to the previous JS handler -- I still don't get any error reported. The app freezes, so I think that supports the theory that even a JS error causes a fatal crash before the error is sent to HB.

I agree.

**Comment by BethanyBerkowitz** [comment]
Ok, getting back to this after some time away. It turns out I was having issues with my setup due to some kind of caching, I think. When running in Release mode, android doesn't seem to re-build, even when I blew away node_modules and re-installed. Turned out I also needed to blow away `android/app/build`, or else I was running an old version of the code. 

So the duplicate iOS error is still a concern, but missing android errors are not, thankfully.

**Comment by andreybutov** [comment]
@subzero10 Isn't the resolution to the duplicate JS error part of @BethanyBerkowitz 's PR here: https://github.com/honeybadger-io/honeybadger-js/pull/1069

**Comment by subzero10** [comment]
> @subzero10 Isn't the resolution to the duplicate JS error part of @BethanyBerkowitz 's PR here: #1069

Good point. I don't know if @BethanyBerkowitz's PR covers all cases for duplicate js errors. @BethanyBerkowitz can you please clarify whether this issue will be resolved with your PR or if @andreybutov needs to take a further look?

**Comment by subzero10** [comment]
OK then!
@andreybutov I assigned this issue back to @BethanyBerkowitz.
@BethanyBerkowitz I added a "closes" keyword to your PR so that it will automatically close this issue as soon as your PR is merged 👌.
