### ISSUE TITLE
Vue and beforeNotify does not work

### ISSUE THREAD

**Issue by knobel-dk** [honeybadger-io/honeybadger-js#1065]
## What are the steps to reproduce this issue?
1. In a fresh Vue 3 + Vite add this in app.js:
```
app.use(HoneybadgerVue, { 
    apiKey: "VERY_SECRET_KEY",
    environment: import.meta.env.MODE,
    revision: "VERY_UNIQUE_BUILD_STRING",
    beforeNotify: (notice) => {
        console.error(notice)
        if (notice.message.includes('UnhandledPromiseRejectionWarning: Error: Request failed with status code 500')) {
            return false;
        }
        if(notice.message === "ResizeObserver loop limit exceeded") {
            return false;
        }
        return true;
}
    }
)
```
4. Encounter one of these exceptions in prod.

## What happens?
The console outputs *[Honeybadger] Error report sent ⚡ https://app.honeybadger.io/notice/c20ac8a8-601a-48ae-8bb3-72d7ed70f1c3* and the error is recorded in HoneyBadger

## What were you expecting to happen?
Nothing should have been sent to Honeybadger.

## Any logs, error output, etc?
…

## Any other comments?
…

## What versions are you using?
**Operating System:** Ubuntu
**Package Name:** "@honeybadger-io/js": "^5.3.0" and "@honeybadger-io/vue": "^5.3.0"
**Package Version:** 5.3.0
**Browser Version:** Any

**Comment by subzero10** [comment]
Hello @knobel-dk, thanks for submitting an issue!

The `beforeNotify` field is not part of the configuration object.
The function `beforeNotify` is available through the `Honeybadger` singleton.

Therefore, in order to configure a `beforeNotify` handler, you can do one of the following:
```
// access Honeybadger singleton through the Vue app instance
app.$honeybadger.beforeNotify(notice => { /* ... logic goes here */ });
```

or

```
// import Honeybadger singleton
import Honeybadger from @honeybadger-io/js;

// this should go after the Vue plugin installation (app.use(HoneybadgerVue, {}))
Honeybadger.beforeNotify(notice => { /* ... logic goes here */ })
```

I hope this helps! Let me know if otherwise!
