### ISSUE TITLE
[react-native] Can't get source maps to work

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#1066]
A user reached out with the following issue:

> We have recently switched to React Native from Ionic and have needed to reconfig our process for uploading to HoneyBadger. I have followed these steps - https://docs.honeybadger.io/lib/react-native/ and have successfully implemented it. I'm able to generate errors, and log things in console and to the platform. I generated sourcemaps and have it as part of the build process. I can see in HB that my errors have the correct associated revision, and the sourcemaps have that same revision, but still being shown that I have no sourcemaps available for that issue.
> 
> Do I need file extensions on the sourcemap-ios / sourcemap-android? Am I uploading them incorrectly? Here is my curl request that I'm making after the maps have been generated.
> 
> curl https://api.honeybadger.io/v1/source_maps \
>   -F api_key=$PROJECT_API_KEY \
>   -F revision=$HONEYBADGER_REVISION \
>   -F minified_url=URL_TO_A_ZIP_ARCHIVE \
>   -F source_map=@$CURRENT_DIRECTORY/sourcemap-ios \
>   -F minified_file=@$CURRENT_DIRECTORY/sourcemap-ios
> Same for the android one.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_mr5i9)

**Comment by s-bridges** [comment]
Thank you for opening this for me @subzero10 !

**Comment by BethanyBerkowitz** [comment]
@s-bridges, in investigating your issue, we've found some problems with how we're handling sourcemaps in the react-native package. For the moment, please hang on tight while we look into it. You should still be able to get errors reported, just without the sourcemaps for the moment. Thanks again for bringing this to our attention!
