### ISSUE TITLE
Errors on generateMetaData are not being reported on nextJS 13

### ISSUE THREAD

**Issue by mcAnastasiou** [honeybadger-io/honeybadger-js#1095]
## What are the steps to reproduce this issue?
In nextJS 13 with the app directory, errors that are being produced in [generateMetaData](https://nextjs.org/docs/app/api-reference/functions/generate-metadata) are not being monitored

## What were you expecting to happen?
To be monitored on honeybadger

**Comment by subzero10** [comment]
Hello @mcAnastasiou, can you provide some example code to reproduce this?
In #1096, I was able to throw an error in `generateMetadata` and see it reported on Honeybadger.
