### ISSUE TITLE
Errors reported from different javascript clients share the same notifier

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#1097]
## What are the steps to reproduce this issue?
<img width="1129" alt="image" src="https://github.com/honeybadger-io/honeybadger-js/assets/5813382/071762fb-ea18-4175-b5b7-8956c76a67d5">
The error shown above was reported from the nextjs package.

## What happens?
The client shown in Honeybadger dashboard appears to be the js package.

## What were you expecting to happen?
The client shown in Honeybadger dashboard should be the nextjs package.

## Any logs, error output, etc?
n/a

## Any other comments?
This is most probably because our javascript integrations use the js package to report errors.

## What versions are you using?
**Package Name:**  @honeybadger-io/nextjs
**Package Version:** 5.6.1

**Comment by BethanyBerkowitz** [comment]
@subzero10 This is also true for the React package -- here's an error reported from that. Is there a chance this was the desired behavior? I have no real preference... but if we update this for one package, we should check all the packages. 

<img width="856" alt="Screen Shot 2023-06-20 at 2 01 15 PM" src="https://github.com/honeybadger-io/honeybadger-js/assets/16493493/f4b67e20-fbfe-4b2b-aa18-9a5a71685e84">

The react-native package does show its own version, but that's because it depends on `core`, not on `js`. 
<img width="856" alt="Screen Shot 2023-06-20 at 2 04 04 PM" src="https://github.com/honeybadger-io/honeybadger-js/assets/16493493/be0e7453-2069-4ee1-89f4-c9d99b4ec79c">

**Comment by joshuap** [comment]
I think we'd need to have a custom `notifier` entry for each sub package for this to work.

**Comment by BethanyBerkowitz** [comment]
> I think we'd need to have a custom `notifier` entry for each sub package for this to work.

@joshuap agreed, we'd also need to add the ability to set a notifier on the client -- currently the `js` package doesn't accept a notifier and just adds it during `__buildPayload`. 

So @subzero10 I don't think this is a bug, it's a feature request. If this would be useful for us to have for debugging, analytics etc, I'm totally down to do it. My guess is that users don't much care what the notifier shows though.

**Comment by subzero10** [comment]
Hey @BethanyBerkowitz, 

> So @subzero10 I don't think this is a bug, it's a feature request. If this would be useful for us to have for debugging, analytics etc, I'm totally down to do it. My guess is that users don't much care what the notifier shows though.

I tagged as _bug_ because this is not what I expected to see in the Error page, but you can say that it's something we've never worked on so it could be marked as a _feature_. I have no strong opinion.
From our side, I think we should be reporting the correct client, for the sake of consistency.

I was ready to start working on this but I saw that you took it 👌 .
Here's what I would try:
- Create a public method `setNotifier` that is called in the index file of each package just before exporting.
- Or add a `beforeNotifyHandler` for each package, which would set a `notifier` property.
- Read the package's version from package.json or follow the implementation of the js package on how to set the `__VERSION__` string with rollup. If we can read it from package.json, can we replace the `__VERSION__` string replace with rollup in the js package as well?

**Comment by BethanyBerkowitz** [comment]
@subzero10, if you prefer to work on it, that's fine by me! I was just in the market for the next thing... but I'm still finishing react native Jest tests so I'm not in a rush.
