### ISSUE TITLE
honeybadger-react package.json peer dependency requests only 4.x || 5.x honeybadger-js

### ISSUE THREAD

**Issue by larvacea** [honeybadger-io/honeybadger-js#1098]
## What are the steps to reproduce this issue?
1. Execute `yarn install`

## What happens?
Yarn complains:
```
 foobar@workspace:. provides @honeybadger-io/js (p26574) with version 6.1.2, which doesn't satisfy what @honeybadger-io/react requests
```

## What were you expecting to happen?
I would prefer no peer-requirement message. Happily the react module works perfectly well with its 6.1.2 @honeybadger-io/js module peer.

## Any logs, error output, etc?
The offending lines in package.json:
```
  "peerDependencies": {
    "@honeybadger-io/js": "4.x || 5.x",
```

## Any other comments?
Thanks! If you would prefer that I author the one-line pull request, I certainly can. Or, of course, you can do the one-liner yourselves, just as you prefer.

## What versions are you using?
**Operating System:** Ubuntu 22.04.2
**Package Name:** @honeybadger-io/react
**Package Version:** 6.0.4
**Browser Version:** …

**Comment by BethanyBerkowitz** [comment]
Thanks for reporting this! Yes, we can definitely update it.
