### ISSUE TITLE
[vue] support peer dependency honeybadger-js v6

### ISSUE THREAD

**Issue by BethanyBerkowitz** [honeybadger-io/honeybadger-js#1102]
Currently has 

```
"peerDependencies": {
    "@honeybadger-io/js": "3.x || 4.x || 5.x"
```

Need to make sure that v6 works, then update this dependency.

**Comment by subzero10** [comment]
> Need to make sure that v6 works, then update this dependency.

It should work, v6 wasn't really an intentional bump.
