### ISSUE TITLE
`honeybadger-copy-config-files` doesn't check `src/`

### ISSUE THREAD

**Issue by mikew** [honeybadger-io/honeybadger-js#1129]
## What are the steps to reproduce this issue?
1. move next folders to `src/`
2. run `npx honeybadger-copy-config-files`

## What happens?
No `_error.tsx` is generated.

## What were you expecting to happen?
An `_error.tsx` to be generated in `src/pages/`

## Any logs, error output, etc?
…

## Any other comments?
…

## What versions are you using?
**Operating System:** …
**Package Name:** …
**Package Version:** …
**Browser Version:** …

**Comment by subzero10** [comment]
Hey @mikew, thanks for reporting an issue!

If I understand correctly, you are using the optional src directory, as mentioned in the [documentation](https://nextjs.org/docs/app/building-your-application/configuring/src-directory).
We can update the script to account for that.

While you wait, you can do the following as a workaround:
- create a `pages` folder in the project root
- run `npx honeybadger-copy-config-files`
- move the new `pages/_error.tsx` file to `src/pages/_error.tsx`
- remove `pages` folder from root

**Comment by subzero10** [comment]
@mikew This should be available with [@honeybadger-io/nextjs@5.7.0](https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io%2Fnextjs%405.7.0)!
