### ISSUE TITLE
`npx honeybadger-copy-config-files` is not working

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#1186]
Script is not built as a commonjs module.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_scn6p)

**Comment by geraldinefiser** [comment]
Would love to get this fix. 

I was following the instructions to get Honeybadger on my Nextjs app but encountered this "SyntaxError: Unexpected token 'export'" when trying to npx honeybadger-copy-config-files

**Comment by subzero10** [comment]
@geraldinefiser This is fixed with `@honeybadger-io/nextjs@5.7.5`!
