### ISSUE TITLE
JS docs do not list tags as an additional option for `honeybadger.notify` on "reporting errors" page

### ISSUE THREAD

**Issue by hislopzach** [honeybadger-io/honeybadger-js#1239]
## What are the steps to reproduce this issue?
1. visit https://docs.honeybadger.io/lib/javascript/guides/reporting-errors/#additional-options

## What happens?
JS docs do not list tags as an additional option for `honeybadger.notify`
https://docs.honeybadger.io/lib/javascript/guides/reporting-errors/#additional-options

## What were you expecting to happen?
The tagging errors page shows that you can pass `tags` in the additional options https://docs.honeybadger.io/lib/javascript/guides/reporting-errors/#additional-options. I would expect to see this option in the reporting errors section as well

## Any logs, error output, etc?
…

## Any other comments?
…

## What versions are you using?
**Operating System:** …
**Package Name:** honeybadger-js
**Package Version:** …
**Browser Version:** …

**Comment by subzero10** [comment]
Hey @hislopzach, thanks for reporting this oversight! We'll add the `tags` property asap.

**Comment by subzero10** [comment]
Done!

**Comment by hislopzach** [comment]
Thanks for the quick response!
