### ISSUE TITLE
Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by clupprich** [honeybadger-io/honeybadger-js#1338]
## What are the steps to reproduce this issue?
1. Add Honeybadger to a Vue (3) project per the [docs](https://docs.honeybadger.io/lib/javascript/integration/vue3/?projectToken=hbp_XtteaszLyuTLbNBsMOT59zAVU4QRqW1uaTkM)
2. Trigger an exception in your application

## What happens?

No matter which browser I'm using (Safari, Chrome, Firefox), Honeybadger is failing to send the exception and instead shows the following error in the Console:

```
[Honeybadger] Error report failed: an unknown error occurred. message=Refused to set unsafe header "User-Agent"
```

## What were you expecting to happen?
The captured exception should be sent to Honeybadger.

## Any other comments?
…

## What versions are you using?
**Operating System:** MacOS 14.4.1
**Package Name:** @honeybadger-io/vue, @honeybadger-io/js
**Package Version:** @honeybadger-io/vue: 6.1.21, @honeybadger-io/js: 6.9.1
**Browser Version:** Safari 17.4.1, Firefox 125.0.2, Chrome 124.0.6367.92

**Comment by subzero10** [comment]
No worries @clupprich! It happens! 😄
