### ISSUE TITLE
Middleware not being built if honeybadger.edge.config.js file is not present

### ISSUE THREAD

**Issue by sayoojtmc** [honeybadger-io/honeybadger-js#1348]
## What are the steps to reproduce this issue?
1. Create a Next.js app with page router
2. Add a basic middleware.js file
3. Setup honeybadger without the `honeybadger.edge.config.js` file
4. Run `yarn build` 

## What happens?
middleware.js is not being shown in the build output. Middleware code does not execute when I run `yarn start`.

## What were you expecting to happen?
middleware.js file to be shown in the build output

## Any logs, error output, etc?
None.

## Any other comments?
I've debugged the issue, there seems to be a bug in `injectHoneybadgerConfigToEntry` when handling the case where config file is not present:
https://github.com/honeybadger-io/honeybadger-js/blob/1554425d31531682697eb0f846985ac024e0f6b0/packages/nextjs/src/index.ts#L71-L73

When I changed it to this:
```js
if (!hbConfigFile) {
    const result =
      typeof originalEntry === "function"
        ? await originalEntry()
        : { ...originalEntry };

    return result;
  }
```
the middleware is getting built.

## What versions are you using?
**Operating System:** MacOS 14.4 
**Package Name:** Next.js 13.4 with page router

**Comment by subzero10** [comment]
Hey @sayoojtmc, thanks for reporting an issue! We'll take a look and come back to you.

**Comment by sayoojtmc** [comment]
Hey @subzero10 , any update on this? I'd be happy to raise a PR for this.

**Comment by subzero10** [comment]
Hey @sayoojtmc, I just submitted this [PR](https://github.com/honeybadger-io/honeybadger-js/pull/1356), which is identical to your fix. Thanks again!
