### ISSUE TITLE
Can I just access the `uploadSourcemaps` function on its own?

### ISSUE THREAD

**Issue by benwalsh** [honeybadger-io/honeybadger-js#1374]
## What are the steps to reproduce this issue?
1. If I add the step `config.devtool = 'source-map';` to my `nuxt.config.js` file and run `nuxt build`, I get the `.map` files I want.
2. If I do this in conjunction with:

```
config.plugins.push(new HoneybadgerSourceMapPlugin({
  apiKey,
  assetsUrl,
  deploy: { environment: process.env.ENVIRONMENT, repository },
  revision: process.env.APP_REVISION
}));
```
then I get a whole lot of effectively empty/trivial case `.map` files that look like this:
`{"version":3,"sources":[],"names":[],"mappings":"","file":"70.1d6ca9330af1e997ff05.js","sourceRoot":""}`

I don't really mind this as I can get the files I want, but I could just skip whatever build step is happening in `HoneybadgerSourceMapPlugin` and use the `uploadSourcemaps` logic on its own, that would save me a lot of tedious work required to upload all the generated files individually.

**Comment by subzero10** [comment]
Hey @benwalsh, thanks for submitting an issue!
🤔 I don't see why other kinds of files would be generated with the plugin - we are not generating any files. The plugin only [finds](https://github.com/honeybadger-io/honeybadger-js/blob/master/packages/webpack/src/HoneybadgerSourceMapPlugin.js#L30) the generated assets and uploads them to Honeybadger. Can I reproduce this with a minimal Nuxt.js app and Honeybadger's webpack plugin?

**Comment by benwalsh** [comment]
So the exact same code is generating the correct sourcemaps on my local MacBook Pro but in our deployed environment Ubuntu 22.04 LTS it's generating empty files.

![Screenshot 2024-07-26 at 15 37 02](https://github.com/user-attachments/assets/6f446422-ad27-408d-9cd2-df3338b59530)
![Screenshot 2024-07-26 at 15 37 13](https://github.com/user-attachments/assets/3074cde7-f1fe-46ac-adc1-40c7a6bff3fd)

**Comment by benwalsh** [comment]
OK whatever's going on here it clearly isn't related to Honeybadger, I'll close this.
