### ISSUE TITLE
Rollup plugin does not upload source maps to staging environments

### ISSUE THREAD

**Issue by mgreca** [honeybadger-io/honeybadger-js#1408]
## What are the steps to reproduce this issue?
1. Create a vite application
2. Install @honeybadger-io/rollup-plugin
3. Try to build in other environments different than production

## What happens?
Source maps are not uploaded if the environment is not "production".
The plugin is checking if `NODE_ENV === "production"` [in this line ](https://github.com/honeybadger-io/honeybadger-js/blob/3ba3168506a016cbf8a17c6301843a4900010ed6/packages/rollup-plugin/src/index.ts#L16). If it is not production, it won't upload source maps.

## What were you expecting to happen?
It should upload to all environments except the development environments like dev, development or test. In my case, I need to upload to `staging`

## What versions are you using?
**Package Name:** @honeybadger-io/rollup-plugin
**Package Version:** 5.9.3

**Comment by subzero10** [comment]
Hey @mgreca, thank you for submitting an issue.
I've created #1412 to address your issue. It's pending review, but it should be merged soon.

**Comment by subzero10** [comment]
@mgreca [@honeybadger-io/rollup-plugn@5.10.0](https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io/rollup-plugin%405.10.0) includes an option to configure development environments to decide whether source maps should be updated or not.
