### ISSUE TITLE
Vue 3 composition API support

### ISSUE THREAD

**Issue by spiffytech** [honeybadger-io/honeybadger-js#1413]
The Honeybadger Vue plugin does not appear to support the Vue 3 composition API.

The Honeybadger docs say to access `this.$honeybadger`, but components using the composition API do not have `this`, so there's no way to access the Honeybadger instance from a component (except the [extremely-discouraged](https://v3.ru.vuejs.org/api/composition-api.html#getcurrentinstance) internal API, `getCurrentInstance().proxy.$honeybadger`)

I think the normal composition API would be for the module to export a `useHoneybadger` function, or possibly to use `provide`/`inject`.

**Comment by subzero10** [comment]
Hey @spiffytech, thank you for reporting an issue!

I am adding this to our backlog; hopefully I'll be able to take it in the next 3-4 weeks, though note that PRs are always welcome if you want to give it a go!

**Comment by subzero10** [comment]
Hey @spiffytech, it seems to me that all we need to do is export a function `useHoneybadger` to return an instance of Honeybadger.
Note: You'd still need to setup Honeybadger in your main file (i.e. `main.ts` or `main.js`) to register global handlers (such as `window.onerror`).

What do you think of the following?
```
<script setup>
import { useHoneybadger } from '@honeybadger-io/vue'
const honeybadger = useHoneybadger()

function notify() {
  honeybadger.notify('Hello from Vue 3!')
}
</script>
```

**Comment by spiffytech** [comment]
LGTM!

**Comment by subzero10** [comment]
`useHoneybadger` should be available with [v6.2.0](https://github.com/honeybadger-io/honeybadger-js/releases/tag/%40honeybadger-io%2Fvue%406.2.0)!

**Comment by spiffytech** [comment]
Confirmed, I sent a test notification from Vue 3. Thanks!

**Comment by subzero10** [comment]
Cool, that was quick!
