### ISSUE TITLE
Webpack + honeybadger-js + Firefox extension interfering with mint.intuit.com

### ISSUE THREAD

**Issue by akshaysmurthy** [honeybadger-io/honeybadger-js#145]
## What are the steps to reproduce this issue?
1. Install honeybadger-js using package.json
2. Load it in the content script  - `import Honeybadger from 'honeybadger-js';`
3. Log in to https://mint.intuit.com (You can create a free account if you don't have one)

## What happens?
The page does not load, instead has some errors:
1. `Error: Permission denied to access property "apply"`
2. `TypeError: window.ADRUM.events.VPageView is not a constructor`

## What were you expecting to happen?
The dashboard page should have loaded. 

## Any logs, error output, etc?
1. `Error: Permission denied to access property "apply"`
2. `TypeError: window.ADRUM.events.VPageView is not a constructor`

## Any other comments?
This does not happen with our Chrome extension. We are using an older version of the honeybadger-js v0.5.5, but saw the same issue with the current version as well.

## What versions are you using?
**Operating System:** Mac
**Package Version:** 0.5.5
**Browser Version:** Firefox 67

**Comment by joshuap** [comment]
I'm going to close the issue report here since we're handling this through our support system. Long story short, your mileage may vary w/ honeybadger.js inside a webextension in Firefox. There seems to be problems with wrapping the global `window.onerror` handler inside the extension. If we find out what it is, I'll update this issue.

**Comment by ybentz** [comment]
Hey @joshuap, did you end up figuring out exactly what's going on here? I just encountered the exact same issue with my extension. Thanks!
