### ISSUE TITLE
lib errors if body tag not yet processed

### ISSUE THREAD

**Issue by stevenjonescgm** [honeybadger-io/honeybadger-js#18]
In Chrome 32.0.1700.107
I am investigating adding honeybadger-js to my project, and plan to use ```onerror: true``` for the first bit to get an idea what areas are worth explicit try-catches.
When testing the integration, I first caused an exception just after initializing the lib while inside the head.

Uncaught TypeError: Cannot call method 'appendChild' of null honeybadger.js?body=1:1414
Honeybadger._crossDomainPost honeybadger.js?body=1:1414
Honeybadger._sendRequest honeybadger.js?body=1:1407
Honeybadger.notify honeybadger.js?body=1:1376
Honeybadger._handleTraceKitSubscription honeybadger.js?body=1:1435
notifyHandlers honeybadger.js?body=1:146
traceKitWindowOnError honeybadger.js?body=1:192

I don't have the time right now to make and test a pr, but I expect the solution to be appending the tracking pixel to head or deferring the append until onload (maybe if document.body is nil)

**Comment by joshuap** [comment]
This should be resolved now.
