### ISSUE TITLE
How to use as a webpack external?

### ISSUE THREAD

**Issue by akrawchyk** [honeybadger-io/honeybadger-js#208]
## What are the steps to reproduce this issue?
1. Install Honeybadger with a script tag: `<script src="https://js.honeybadger.io/v2.0/honeybadger.min.js"></script>`
2. Configure it: `<script>Honeybadger.configure({ apiKey: 'XXX' })</script>`
3. Setup webpack external: `webpack.config.js`: `externals: { 'honeybadger-js': 'Honeybadger' }`
4. Import in webpack app: `import Honeybadger from 'honeybadger-js`
5. Send error: `Honeybadger.notify('test')`

## What happens?

Error is thrown complaining about missing API Key.

## What were you expecting to happen?

Error is successfully sent to Honeybadger.

## Any logs, error output, etc?

Logged to console when trying to `Honeybadger.notify('test')`:

`[Honeybadger] Unable to send error report: no API key has been configured`

## Any other comments?

I'm doing this in a Vue app, so also attempting to configure `@honeybadger-io/honeybadger-vue` using the Honeybadger external. I would configure Honeybadger in the Vue app, except we have many of them and they are all mounted in a Rails view (which is where the Honeybadger configuration is provided by the script tags).

## What versions are you using?
**Operating System:** macOS 10.14.6
**Package Version:** 2.0
**Browser Version:** Mozilla Firefox 70.0b5 (64-bit)

**Comment by joshuap** [comment]
@akrawchyk I've never encountered this type of set up before, so I'm not quite sure. Does `import Honeybadger from 'honeybadger-js` import the global `window.Honeybadger` object? Have you tried configuring it again inside webpack?

**Comment by akrawchyk** [comment]
> Does import Honeybadger from 'honeybadger-js import the global window.Honeybadger object? 

This is my understanding, when I dug through the bundle there was a simple `module.exports = Honeybadger` which should just be exporting the singleton.

> Have you tried configuring it again inside webpack?

Yes, I've tried doing all the config using the webpack imported `Honeybadger`, and it works (!?) which is also confusing. I would much prefer do it this way but the effort it would take to do this outweighs the benefits for me right now.

Also, if DON'T configure within webpack and take only the global configuration, when I `console.log('Honeybadger')` from the webpack import, I still see the configuration attached to the `Honeybadger` object, as expected from here https://github.com/honeybadger-io/honeybadger-js/blob/master/src/builder.js#L449-L454.

I'm really confused by this since it seems like it should just work™️, am I running into some weird scoping/singleton issues?

**Comment by akrawchyk** [comment]
@joshuap Thanks for looking at this! I made an example repo to reproduce this at https://github.com/akrawchyk/honeybadger-webpack-externals-example/commit/8ede67483d8328e1a22abce67ed9e22d6b7d6a1e

Funny enough, it does work when the app is hot-reloaded after making changes. But when loading the app initially, I still see the error message about no API key configured.

Also, it appears like `honeybadger-js` is added as a dependency, but I verified the `<script>` is what's used by webpack:

<img width="1680" alt="Screen Shot 2019-09-16 at 6 23 36 PM" src="https://user-images.githubusercontent.com/903716/64997926-264dfe00-d8b0-11e9-8b7e-d2d134010afd.png">

**Comment by joshuap** [comment]
@akrawchyk thanks for the repo, this will be a huge help. I'll take a look and let you know what I find. Planning to look into this tomorrow.

**Comment by akrawchyk** [comment]
Now that I'm looking at the changes in isolation, I have a feeling this has to do with script eval order. I'm thinking the `DOMContentLoaded` is causing a race condition where Honeybadger is configured AFTER the app loads...

**Comment by joshuap** [comment]
@akrawchyk that sounds promising. Were you able to confirm anything there? Let me know if you still think there is an issue on our end for me to look into (just checking in case you didn't mean to close this).

**Comment by akrawchyk** [comment]
@joshuap thanks for checking, I meant close it because `DOMContentLoaded` was the culprit. Webpack externals work fine 😄
