### ISSUE TITLE
Exponential slowdown when running Jest tests with honeybadger included

### ISSUE THREAD

**Issue by aub** [honeybadger-io/honeybadger-js#242]
## What are the steps to reproduce this issue?
1. I have a React project that uses Honeybadger for error notification. It has a test suite with a bunch of very simple tests using enzyme's `mount` function to render the components and make sure they work ok.
2. When I run this test suite after adding Honeybadger to my code, the suite slows to a crawl and then locks up completely so that I have to kill it manually.

## What happens?
The tests seem to go into an infinite loop. With some logger debugging, I found that what happens is that Honeybadger is being reinitialized with each test. During its initialization, it installs all of its instrumentation in the form of event handlers. Since it hasn't removed the handlers from the previous test(s) they start piling up, and this makes each test execution slower than the previous one.

Note that there's a little bit of conjecture here... I'm not sure why/if enzyme is holding onto the handlers from the previous test or how one might reset it. I've added console logging and seen it print out tons of logs when the handlers fire though.

## What were you expecting to happen?
Only a single instrumentation of Honeybadger so the tests don't slow down.

## Any logs, error output, etc?
…

## Any other comments?
…

## What versions are you using?
**Operating System:** MacOS 10.15.1
**Package Version:** 1.0.4
**Browser Version:**

**Comment by joshuap** [comment]
Hey @aub, thanks for the report. How are you including honeybadger-js in your code? Our library guards against the instrumentation being installed more than once by the global instance, but doesn't expect to be included multiple times on a page, for instance. I'm not sure what would happen in that case.

**Comment by aub** [comment]
I've got `honeybadger-js` and `@honeybadger-io/react` as dependencies in my package.json file, and then in the component modules where I need access to honeybadger I import it with:

`import Honeybadger from 'honeybadger-js'`

Maybe that's the wrong approach? I can do a quick test to verify, but I _think_ this problem is specific to the tests. We're using Jest with Enzyme and jsdom, and it seems like jsdom is supposed to reset its virtual browser after each test, but that doesn't jive with the pileup of handlers I'm seeing.

**Comment by joshuap** [comment]
I think you should be able to import multiple times and it will return the same singleton object. It would be good to verify that in your project. It does sound like something strange is going on with the test setup, though.

**Comment by aub** [comment]
Yep, verified that it only initializes once in the regular app. I'm not quite sure where to go from here with the tests, but I'll see if I can figure out how/when jsdom reinitializes the virtual browser.

**Comment by joshuap** [comment]
Thanks! Also, if all else fails, could you try reproducing in a sample repo/gist that we can check out?

**Comment by aub** [comment]
Ok, [here's a repo where it's reproduced](https://github.com/aub/honeybadger-jsdom). It's just a `create-react-app` app that's been ejected with the testing setup to use enzyme and jsdom and then 250 copies of the same simple test that mount the `App` component. That component imports Honeybadger and does some stuff with it, although only the configuration part of that should actually be being executed. Even then, I think if you commented out the configuration line it would still exhibit the slowdown.

I haven't yet tried to find the cause of the problem using this app but will start looking into it now. I'm not that excited about digging into jsdom's source. ;)

**Comment by aub** [comment]
@joshuap I don't suppose you have any ideas on this one? I'm getting nowhere so far but will spend some more time on it this morning.

**Comment by aub** [comment]
One thing I've figured out is that the only events that pile up are the EventTarget ones. If I remove `EventTarget` from [this line](https://github.com/honeybadger-io/honeybadger-js/blob/master/src/builder.js#L784) then it works fine. :sob:

**Comment by joshuap** [comment]
@aub I don’t have any ideas without diving into the code. I’m traveling this week but I will plan to check out the example repo and take a look at what it’s doing next week. Thanks for the extra info!

**Comment by joshuap** [comment]
@aub I did some research, and it seems that it's a known issue that jsdom doesn't completely clean up state between individual tests. That seems weird to me, but there's nothing I can do about it. :shrug: 

I came up with the following workaround which fixes the issue in your example repo: https://github.com/honeybadger-io/honeybadger-js/pull/255/files

**Comment by aub** [comment]
Thank you so much @joshuap! This does solve the problem.
