### ISSUE TITLE
No way to use fingerprinting

### ISSUE THREAD

**Issue by panrafal** [honeybadger-io/honeybadger-js#25]
I couldn't find a way to use fingerprinting as in here:

http://docs.honeybadger.io/article/36-exception-grouping

Using `fingerprint` as an option in `notify` obvously doesn't work as it's not handled in the Notice class. Could you add it to the API?

**Comment by joshuap** [comment]
Sorry for not responding to this sooner, I just noticed the reply... :\ If you're still having trouble with fingerprinting, please email me at support@honeybadger.io and I'll check out your project.
