### ISSUE TITLE
Cannot connect to https://js.honeybadger.io from IE8

### ISSUE THREAD

**Issue by bswinnerton** [honeybadger-io/honeybadger-js#27]
It appears that in Internet Explorer 8, the following URL does not resolve: https://js.honeybadger.io/v0.2/honeybadger.min.js. This means that when trying to use the code snippet provided in the honeybadger-js [README.md](https://github.com/honeybadger-io/honeybadger-js/blob/cca415c65948c4b965ac464e35750cde84d08be0/README.md):

```html
<script src="//js.honeybadger.io/v0.2/honeybadger.min.js" type="text/javascript"></script>
```

The schemaless connection will fail, and the following error appears in Javascript:

![screen shot 2015-01-20 at 11 24 10 am](https://cloud.githubusercontent.com/assets/934497/5822222/2be606ac-a0a0-11e4-86fa-2c1b96d6da1a.png)

Below is a screenshot of the failed connection:

![screen shot 2015-01-20 at 12 27 28 pm](https://cloud.githubusercontent.com/assets/934497/5822183/ba8a2d4e-a09f-11e4-97db-512e87ce9583.png)

And while you can try to fall back on an HTTP schema, the following error is shown in Internet Explorer 8 when the site in question is browsed via HTTPS, which leads to a less than optimal user experience:

![screen shot 2015-01-20 at 12 15 00 pm](https://cloud.githubusercontent.com/assets/934497/5822197/d7b11efa-a09f-11e4-8dd9-de792fef985d.png)

**Comment by joshuap** [comment]
Hi Brooks, thanks for the bug report. I think you can solve that problem by just using the HTTPS version of honeybadger.min.js all the time:

```js
<script src="https://js.honeybadger.io/v0.2/honeybadger.min.js" type="text/javascript"></script>
```

I'll probably end up updating our instructions to recommend that.

**Comment by bswinnerton** [comment]
Hi @joshuap, unfortunately browsing to https://js.honeybadger.io/v0.2/honeybadger.min.js in Internet Explorer returns a connection error, so that's not possible.

**Comment by starrhorne** [comment]
FWIW, it seems to work ok for me on ie8/win7.

**Comment by bswinnerton** [comment]
I'm running IE8 on Windows XP from [Modern.IE](https://www.modern.ie/en-us/virtualization-tools).

**Comment by joshuap** [comment]
What is the connection error returned for https://js.honeybadger.io/v0.2/honeybadger.min.js?

**Comment by bswinnerton** [comment]
I'm not entirely sure how to get the numeric error number from Internet Explorer, but found [this](http://windows.microsoft.com/en-us/windows/get-help-website-http-errors#1TC=windows-81) from Microsoft's KB suggesting that it's a 500. An expanded version of the error can be found here:

![screen shot 2015-01-20 at 12 45 45 pm](https://cloud.githubusercontent.com/assets/934497/5822450/4565b792-a0a2-11e4-9ecd-c492cd86c357.png)

**Comment by starrhorne** [comment]
I have duplicated this problem on ie8/xp. 

It seems to have something to do with SSL. The non-ssl url works fine. The ssl url results in a "cannot connect to this webpage, maybe the server is offline" error.

**Comment by starrhorne** [comment]
So we identified the problem, and it turns out that most CDNs (including cloudfront, the one we use) don't support SSL on Windows XP.

We'll investigate alternative hosting arrangements, but for now the quickest solution would be to host the JS library yourself.
