### ISSUE TITLE
Type definition incorrect.

### ISSUE THREAD

**Issue by acklavidian** [honeybadger-io/honeybadger-js#279]
The type definition file dictates that most of the functions provided by the main export return a void value:
https://github.com/honeybadger-io/honeybadger-js/blob/fae5d6178eb08b443dc3a41b1f72f04f050ca58d/honeybadger-js.d.ts#L35
However, it seems this is incorrect upon reviewing the actual source. For instance `configure`:

https://github.com/honeybadger-io/honeybadger-js/blob/fae5d6178eb08b443dc3a41b1f72f04f050ca58d/src/builder.js#L460-L465

**Comment by schontz** [comment]
It should be this:

```ts
static configure(config: Config): Honeybadger;
```

And the following should be fixed in the react project:

https://github.com/honeybadger-io/honeybadger-react/blob/master/honeybadger-react.d.ts#L5

It should be something like:
```ts
declare module "@honeybadger-io/react" {
  import { Component } from "react";
  import Honeybadger from "honeybadger-js"; // NEW

  interface Props {
    honeybadger: Honeybadger; // CHANGED
    children: React.ReactNode;
    ErrorComponent?: React.ReactNode | Function;
  }
```

**Comment by acklavidian** [comment]
Should it not be:
```typescript
interface Props {
    honeybadger: typeof Honeybadger; // CHANGED
}
?

**Comment by schontz** [comment]
@acklavidian Not necessary.

**Comment by joshuap** [comment]
@acklavidian @schontz I'm not super familiar with TypeScript and need to defer to your knowledge on this. I agree that the type definition looks incorrect for that function (and any others like it). PRs to both projects welcome. :)

**Comment by schontz** [comment]
@joshuap My changes in the previous comment should be all you need to do.

> It should be this:
> 
> ```ts
> static configure(config: Config): Honeybadger; // was ': void'
> ```
> 
> And the following should be fixed in the react project:
> 
> https://github.com/honeybadger-io/honeybadger-react/blob/master/honeybadger-react.d.ts#L5
> 
> It should be something like:
> 
> ```ts
> declare module "@honeybadger-io/react" {
>   import { Component } from "react";
>   import Honeybadger from "honeybadger-js"; // NEW
> 
>   interface Props {
>     honeybadger: Honeybadger; // CHANGED
>     children: React.ReactNode;
>     ErrorComponent?: React.ReactNode | Function;
>   }
> ```

**Comment by schontz** [comment]
I tested the changes to `module "@honeybadger-io/react"`, and it works as expected. The changes need to be made in both repos for it to work properly, so the dependency on this repo in the react one would need to be updated.

**Comment by joshuap** [comment]
@acklavidian @schontz OK, here you go. Do these look correct?

https://github.com/honeybadger-io/honeybadger-js/pull/286
https://github.com/honeybadger-io/honeybadger-react/pull/92
