### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by mockdeep** [honeybadger-io/honeybadger-js#29]
We're getting this error from the old android stock browser `Converting circular structure to JSON`. user agent:

```
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; GT-P5210 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

It appears to be originating from within Honeybadger as it is trying to serialize another error. Here's a stack trace:

```
TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at Client._xhrRequest (https://js.honeybadger.io/v0.2/honeybadger.min.js:1:10195)
  at Client._sendRequest (https://js.honeybadger.io/v0.2/honeybadger.min.js:1:8318)
  at Client._send (https://js.honeybadger.io/v0.2/honeybadger.min.js:1:7926)
  @https://js.honeybadger.io/v0.2/honeybadger.min.js 1:5684  
  at d.util.hasFunction.f.(anonymous function) (https://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js:3:492)
  at nrWrapper (https://chalkschools.com/campaigns/glenshire-batie-electronic-form/responses:5:12949)
```

My theory is that the old android browser returns some sort of self-referential error object, which Honeybadger is trying to serialize with `JSON.stringify()`, so it raises a new error. We can try to pre-process this error on our end, but it would be nice if Honeybadger was able to handle it gracefully.

**Comment by joshuap** [comment]
Thanks Robert, I'll work on a fix for that.

**Comment by mockdeep** [comment]
bump on this. We're still seeing it a couple of times a week from older android browsers.

**Comment by joshuap** [comment]
@mockdeep gotcha; I should have time to look at it again this week.

**Comment by joshuap** [comment]
@mockdeep can you check out 09f95b433a426ebc8bc15e43a49c3d8fbb654747 and let me know if http://js.honeybadger.io/honeybadger-0.2.1.min.js fixes the issue? If it does I'll release the update to v0.2 on our CDN.

**Comment by mockdeep** [comment]
Thanks @joshuap I'll give that a try and see how it works out. Unfortunately, we don't have a solid way to reproduce the error, but I'll pop back in here if we see it happen again. The logic looks sound, at any rate.

**Comment by mockdeep** [comment]
Actually, we're using the [rails-assets](https://rails-assets.org/) version of honeybadger-js, so I don't think we have a clean way of updating until you push to bower...

**Comment by joshuap** [comment]
@mockdeep I just released 0.3.0 which should be available via Bower now ([as well as the CDN](http://js.honeybadger.io/v0.3/honeybadger.min.js)). Let me know how it goes!

**Comment by mockdeep** [comment]
Sweet! Will do.

**Comment by mockdeep** [comment]
On bower I'm seeing two packages for honeybadger: `honeybadger.js` and `honeybadger-io--honeybadger-js`. The first one hasn't been updated to version `0.3.0` and the second has. Should we be using the second one?

**Comment by joshuap** [comment]
that's odd, I'm seeing just honeybadger.js here:

http://bower.io/search/?q=honeybadger

it should definitely be just "honeybadger.js". Does our bower.json look OK to you? https://github.com/honeybadger-io/honeybadger-js/blob/master/bower.json

**Comment by mockdeep** [comment]
Hmm, maybe it's a bug on `rails-assets`. I'm seeing this:

![hbadger](https://cloud.githubusercontent.com/assets/80543/8945707/977e3a28-353e-11e5-8913-4ba2d80cee55.png)

**Comment by joshuap** [comment]
@mockdeep rails-assets is showing 0.3.0 for the honeybadger.js entry now. Not sure why there are two entries; feel free to ignore honeybadger-io--honeybadger-js.

**Comment by mockdeep** [comment]
Cool, will give that one a shot. Thanks!

**Comment by joshuap** [comment]
@mockdeep if you try out v0.4.0 of honeybadger.js, you may notice that I am handling circular data structures differently after the rewrite (we are no using plain JS, not CoffeeScript).

Rather than specifically try to remove circular dependencies (which adds a lot of overhead, because you have to iterate over potentially deeply nested objects, I've added a new "max depth" option which will simply not send objects beyond a certain point (the default is 5 nested objects). See [here](https://github.com/honeybadger-io/honeybadger-js/blob/c6d6e0b5f015514edfcc9fddfbb8b619e2bff02e/honeybadger.js#L196). The max depth is configurable via the "max_depth" option.

I think this should handle the circular dependency issues we've seen in the past, but I wanted to make sure to let you know about the difference. If you do encounter any problems please let me know and I will address them.

**Comment by joshuap** [comment]
Also, we are no longer converting data to JSON at all, so that may also solve the same issue.

**Comment by mockdeep** [comment]
Sounds good, I'll keep that in mind.
