### ISSUE TITLE
"'Honeybadger' is undefined" on Windows/IE

### ISSUE THREAD

**Issue by mockdeep** [honeybadger-io/honeybadger-js#30]
We're seeing this error pretty frequently on Windows machines: "'Honeybadger' is undefined". It seems to be almost entirely on Windows XP with IE8, but we've also seen it a handful of times on Windows 7 up to IE10. On Browserstack we see it consistently with XP/8.

**Comment by mockdeep** [comment]
Also just noticed we've got a handful of "Uncaught ReferenceError: Honeybadger is not defined" in Chrome. We're using TrackJS and managed to get a scrap of a stack trace:

```
https: //cdncache-a.akamaihd.net","offerz4u.utop.it"],d=["file://"];Honeybadger.setContext({user_id:window.gon.user_id,user_email:window.gon.user_email,plugins:t()}),Ho
```

Looks like an adware virus is inserting itself into the page, so not sure if there's anything to be done.

**Comment by mockdeep** [comment]
Actually, turns out that's one of our ignores, so that doesn't appear to be the issue.

**Comment by joshuap** [comment]
@mockdeep how are you loading Honeybadger? Is it via the CDN in the head tag, before your other scripts are loaded?

**Comment by mockdeep** [comment]
Yep. In our layout we have exactly:

```haml
  = javascript_include_tag '//js.honeybadger.io/v0.2/honeybadger.min.js'
  = javascript_include_tag 'honeybadger' # our configuration script
```

**Comment by joshuap** [comment]
Hmm, well this could have something to do with the CDN, although I've never seen this before. Did the browser give you any errors related to the honeybadger.min.js file loading in the browsers which had this error? Also, have you tried loading honeybadger.min.js from your own domain?

**Comment by mockdeep** [comment]
I was actually able to reproduce this error by blocking scripts from `honeybadger.io`, so I'm wondering if they have a script blocker enabled. We'll try using the bower version instead.
