### ISSUE TITLE
e[r].test is not a function error w/ ignorePatterns

### ISSUE THREAD

**Issue by larschon** [honeybadger-io/honeybadger-js#340]
I'm having an issue with using ignorePatterns where `Uncaught TypeError: e[r].test is not a function` is thrown. 

It appears to be a problem when using ` for...in`:
https://github.com/honeybadger-io/honeybadger-js/blob/8ed9811754a9c77fd87e95399c4133ab4b3c7b73/src/builder.js#L57

I can see `p: "_super"` when debugging, which is causing the error.
https://github.com/honeybadger-io/honeybadger-js/blob/8ed9811754a9c77fd87e95399c4133ab4b3c7b73/src/builder.js#L58

According to the docs (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in): 

> Given that for...in is built for iterating object properties, not recommended for use with arrays...

I'm now using an older version, with 
`if (msg.match(patterns[p])) { return true; }` 
to compare patterns, which is working fine.  

I'm guessing using `forEach()` to iterate the array of ignorePatterns would be a better option.

**Operating System:** MacOS 10.15.4 
**Package Version:** 2.2
**Browser Version:** Chrome 80.0.3987.163

**Comment by joshuap** [comment]
@larschon thanks for reporting this! I have it on my todo list to take a look this week.
