### ISSUE TITLE
Ability to require with `browserify`?

### ISSUE THREAD

**Issue by mockdeep** [honeybadger-io/honeybadger-js#38]
I'm using `npm` and `browserify` for client side packages and tried adding `honeybadger-js`, but can't `require` it in my application via the package. I'm not sure if there is a canonical preferred way to handle this, but I've seen [some libraries](https://github.com/golmansax/backbone-sortable-collection/blob/master/lib/backbone_sortable_collection.js#L2-L16) add a `module.exports` if it makes sense in the context.

**Comment by mockdeep** [comment]
Or can [honeybadger-node](https://github.com/honeybadger-io/honeybadger-node) be used client side?

**Comment by joshuap** [comment]
@mockdeep no, honeybadger-node can't be used client-side unfortunately. I might be interested in doing a hybrid package but in the past it didn't seem very feasible. In the meantime, we added the `honeybadger-js` package for anyone who wanted to include the client-side version using npm, but I'm not familiar with how to set that up with browserify. I'll have to do some digging on this; the good news is that I am planning to spend some dev time on honeybadger-js soon. :)

In the meantime, can you update this issue with any relevant information you might find?

**Comment by joshuap** [comment]
@mockdeep can you take a look at eee2ac42a073e7952830f3c136b88ebfe3154bbd/76f8e0f506ad42d5fcdb8625ef8226dc26f8feae (on the [instrumentation](https://github.com/honeybadger-io/honeybadger-js/tree/instrumentation) branch and let me know what you think? I ended up going with the UMD pattern (which supports commonjs `exports` (browserify) as well as AMD (requirejs)).

**Comment by mockdeep** [comment]
@joshuap looks like that will do the trick. Thanks!
