### ISSUE TITLE
Console logging references honeybadger source

### ISSUE THREAD

**Issue by rabidpraxis** [honeybadger-io/honeybadger-js#397]
All instrumented logging operations are pointing to the Honeybadger source.

![Screen Shot 2020-07-14 at 10 02 56 AM](https://user-images.githubusercontent.com/85654/87454785-4f671a00-c5b9-11ea-80d3-b8dff2911166.png)

This can be confusing as some users rely on that source to know where their logging calls are referenced from.

**Comment by matej-svejda** [comment]
I think preventing this when Honeybadger notfications are disabled (which I imagine is the default dev-environment) would already help a lot - at elast for me.

**Comment by reabiliti** [comment]
It would be great to fix this :)

**Comment by reabiliti** [comment]
@rabidpraxis hi, do you know if the problem will be solved soon?

**Comment by DryFlyRyan** [comment]
This appears to be done as a side effect by importing the library.

I can see why having this in production would be advantageous, but it really seems like it should be done in response to a config, or at the very least be done within the `Honeybadger.confugure` call.

**Comment by joshuap** [comment]
@DryFlyRyan I like the idea of making it install the instrumentation on the first call to `Honeybadger.configure`. That would also allow us to add config options to optionally disable it. I'll take a look at it this week. 👍

**Comment by joshuap** [comment]
I've released a fix for this on our beta tag on npm:

https://www.npmjs.com/package/honeybadger-js/v/2.3.0-beta.0

You can also find the CDN versions here:

http://js.honeybadger.io/v2.3-beta/honeybadger.js
http://js.honeybadger.io/v2.3-beta/honeybadger.min.js

With this version, the breadcrumbs instrumentation should not be installed in development unless you call `Honeybadger.configure` (which you *must* call at least once to configure your Honeybadger API key). You can also disable certain types of breadcrumbs. Here are the defaults:

```js
Honeybadger.configure({
  breadcrumbsEnabled: {
    dom: true,
    network: true,
    navigation: true,
    console: true
  }
})
```
