### ISSUE TITLE
Browserify compatibility issues. 

### ISSUE THREAD

**Issue by actionnick** [honeybadger-io/honeybadger-js#41]
Followed the README instructions and ran into some issues. 

First thing that didn't work was that the README says to do `var Honeybadger = require("honeybadger");`. This errors out because it can't find `honeybadger`. Instead you have to do  `var Honeybadger = require("honeybadger-js/honeybadger");`

Second thing is that this file doesn't actually seem to be written as a module so `Honeybadger` is just an empty object at this point, but `window.Honeybadger` is present. 

The final working code ended up looking like...
```javascript
require("honeybadger-js/honeybadger");
var Honeybadger = window.Honeybadger;
```

What is the intended behavior here and what should the README reflect?

**Comment by joshuap** [comment]
Browserify support hasn't been released yet (current version is 0.3, master is 0.4 (unreleased), so it won't work if you download honeybadger.js from npm/bower etc. That said, as of today browserify should be fully supported by master. Can you download a new copy of [honeybadger.js](https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger.js) and try it with that? You can see a full working example here: https://github.com/honeybadger-io/honeybadger-js/tree/master/examples/browserify

**Comment by actionnick** [comment]
Ahh okay. You can install packages from NPM through github, so maybe change the README documentation to `var Honeybadger = require("honeybadger-js/honeybadger");` or `var Honeybadger = require("honeybadger-js");` and specify `"main": "./honeybadger.js"` in package.js.

**Comment by joshuap** [comment]
@actionnick make sense, thanks. I made some updates (added the main directive and updated the readme). Because this is a front-end-only lib and the require paths will be different between bower/npm/github, I changed the example paths to make it more obvious that you need to choose one for your environment: "path/to/honeybadger". Btw, does browserify + honeybadger work for you now?

**Comment by actionnick** [comment]
Yes it does with this require `var Honeybadger = require("honeybadger-js/honeybadger");` and this in my package.json, `"honeybadger-io/honeybadger-js"`. Thanks for the help!

**Comment by joshuap** [comment]
Great, happy to help!
