### ISSUE TITLE
Source maps only for Honeybadger

### ISSUE THREAD

**Issue by CGamesPlay** [honeybadger-io/honeybadger-js#42]
I would like to use the source map support for Honeybadger, but I don't want to expose my source maps to the world. How can I accomplish this?

Preferably, I would like to set a project setting to provide a hidden path where the source maps can be located.

I could also distinguish by user agent, although this is obfuscation, not security. Then again minified sources are just obfuscation, so this might be sufficient.

**Comment by starrhorne** [comment]
Hi Ryan, 
 
We send along a special HTTP header with a secret that you can use to authenticate our sourcemap requests. The header is `Honeybadger-Token`.

Assuming your project is a "Client Side JS" project,  go to "Project Settings" > "Sourcemaps" and scroll to the bottom to get your secret. 

If you need to, you can edit the project language by going to "Project Settings" > "Edit". 

Let us know if you have any questions!

**Comment by CGamesPlay** [comment]
This is great. Thanks!

**Comment by starrhorne** [comment]
np!
