### ISSUE TITLE
Broken on IE8

### ISSUE THREAD

**Issue by mockdeep** [honeybadger-io/honeybadger-js#43]
Not sure which browsers you intend to support, but loading honeybadger-js in IE8 causes errors in our application. I suspect there is another error, but Honeybadger throws when reporting it. It seems to be coming from [this line](https://github.com/honeybadger-io/honeybadger-js/blob/15cf70a79e22cc9af27810988e68c71a31ff9c7e/honeybadger.js#L463), saying `'original' is null or not an object'`.

**Comment by joshuap** [comment]
@mockdeep we support down to IE 6, so it sounds like there is a bug. Here's our current CI test matrix:

https://github.com/honeybadger-io/honeybadger-js/blob/master/Gruntfile.js#L2

That instrumentation code *should* be covered by the tests, and we also have a file which you can manually test browser events with [here](https://github.com/honeybadger-io/honeybadger-js/blob/master/spec/events.html), so I'm wondering if there is a conflict with another library or something. Are you doing any polyfilling for older browsers, or using any other libs which do?

**Comment by mockdeep** [comment]
Yeah, we're using [es5-shim](https://github.com/es-shims/es5-shim) for polyfilling. We'll keep digging and see what we can find.

**Comment by mockdeep** [comment]
So it looks like IE versions prior to 9 [don't support `addEventListener`](http://caniuse.com/#feat=addeventlistener). I'm not seeing a polyfill in your code, but the above referenced `instrument` call seems to be expecting the function to be defined. `es5-shim` doesn't define an `addEventListener` function for us because it was added to the spec prior to es5. Do we need to define our own polyfill?

**Comment by joshuap** [comment]
Ah, you know what; I bet we're adding the instrumentation when we shouldn't be, and then maybe some other code which checks for the presence of `addEventListener` is finding ours when it shouldn't. It could be that es5-shim is polyfilling a global object which we're looking for when we add our version of the function. I'm thinking we should just add a check to make sure there is already an `addEventListener` function on each prototype before instrumenting it.

**Comment by joshuap** [comment]
@mockdeep how does this look? a447ea16aea50b45b8405cd997af8a77e04400bd

**Comment by joshuap** [comment]
Looks like sauce labs is having some issues today so I haven't been able to run the build yet.

**Comment by joshuap** [comment]
@mockdeep the fix has been released. Let me know how this works for you now. Thanks!

**Comment by mockdeep** [comment]
:+1: Seems to have done the trick. Thanks!
