### ISSUE TITLE
Testing the API

### ISSUE THREAD

**Issue by vorillaz** [honeybadger-io/honeybadger-js#46]
Hello there, thanks for this quite nice module. In our app we are using honeybadger on production and staging environment as well. I was wondering if there is any proper way to write unit tests against our error handler configuration. 

I think I might replicate your specs but shall we trigger any errors in order to test the app on development as well?

**Comment by starrhorne** [comment]
Hi Theodore, 

Generally we recommend that your tests go up to the point that `Honeybadger.notify` is called. After that I'd rely on our library's specs to ensure that the delivery process happens correctly. 

If you're trying to make sure that a particular error is being automatically captured and reported, you can do so via the [Honeybadger.beforeNotify](https://github.com/honeybadger-io/honeybadger-js#honeybadgerbeforenotify-add-a-callback-to-be-run-before-an-exception-is-reported) callback. Returning false will prevent the error from being sent to our api. 

@joshuap - the primary maintainer of this library - gets back from vacation next week. He might have some thoughts on this as well.

**Comment by joshuap** [comment]
@vorillaz in our unit tests we use [sinonjs](http://sinonjs.org/) to mock the xmlhttprequest API so that live requests aren't made (and we can still verify the requests happen). You could also do that, or your could take @starrhorne's approach of just stubbing the `Honeybadger.notify` call.
