### ISSUE TITLE
Configure API is not consistent

### ISSUE THREAD

**Issue by nshoes** [honeybadger-io/honeybadger-js#48]
The API for `configure` is different between [honeybadger-js](https://github.com/honeybadger-io/honeybadger-js#globally) and [honeybadger-node](https://github.com/honeybadger-io/honeybadger-node#3-set-your-api-key). The browser version requires snake case as keys, and the node version requires camel case. This makes it difficult for people (like myself) who run their code in the browser and test in both the browser and node environment. 

I would argue that camel case would be the right alternative (get your snake case out of my JS 😉), but that is obviously a large breaking change.

Maybe allow camel case as keys and then transform to snake case? I was working on a fix but can't put a lot of time into it now, and wanted to get your thoughts @joshuap.

**Comment by joshuap** [comment]
It looks like api_key and project_root are the only options that differ. I'd be OK with switching to prefer camel case but also keep support for the existing snake case options.
