### ISSUE TITLE
Deprecate ignorePatterns

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#504]
The [`ignorePatterns`](https://docs.honeybadger.io/lib/javascript/reference/configuration.html#configuration-options) config option was added to honeybadger-js before [`beforeNotify`](https://docs.honeybadger.io/lib/javascript/reference/configuration.html#beforenotify-handlers), which can accomplish the same thing:

```js
Honeybadger.configure({
  // ...
  ignorePatterns: [/NoisyError/i, /unwanted error message/i]
})
```

vs:

```js
const ignorePatterns = [/NoisyError/i, /unwanted error message/i]
Honeybadger.beforeNotify(function(notice) {
  if (ignorePatterns.some((p) => p.test(notice.message))) { return false }
})
```

Here are the reasons I'm thinking it makes sense to deprecate `ignorePatterns`:

1. It's redundant
2. It's less powerful than `beforeNotify`, since it's only applied to error messages
3. The name "ignorePatterns" itself is not descriptive of what the patterns are applied to (this could be fixed by renaming it to something like `ignoredMessagePatterns`, but...)

The only argument I can think of for keeping it around (and giving it a more descriptive name) is that it's a convenient shorthand ([see guide for how we currently present both features together](https://docs.honeybadger.io/lib/javascript/guides/reducing-noise.html)).

Edit: we do have a similar option in Ruby, [`exceptions.ignore`](https://docs.honeybadger.io/lib/ruby/gem-reference/configuration.html#configuration-options), which is applied to the error class name.

**Comment by stympy** [comment]
👍
