### ISSUE TITLE
Add option to send API request with POST

### ISSUE THREAD

**Issue by butchler** [honeybadger-io/honeybadger-js#51]
Currently, if the context is too large, the request fails with a `414 Request-URI Too Large` status. If the context could be stored in the data of a  `POST` request, maybe the request would not fail.

I know that this might not be possible in browsers that don't support `XMLHttpRequest`, but if your app requires `XMLHttpRequest` anyway, it would be nice to be able to opt-in to using `POST` to avoid `notify`s possibly failing with `414`s.

The obvious solution would be to just not send so much context, but I would ideally like to send the entire Redux state of the app at the time of the error, which could get very large depending on how much content the app is currently showing.

**Comment by joshuap** [comment]
@butchler thanks for the suggestion! This is already on my todo list, actually. I'm planning on looking into adding support for larger payloads specifically for the purpose of including Redux state early next year.

**Comment by butchler** [comment]
Thank you :)

**Comment by joshuap** [comment]
I've reverted the change I made related to this issue for now; it's still on the roadmap, but I need to think about the approach a while longer so that we can maintain cross-browser support.

**Comment by butchler** [comment]
That's fine. Should this issue be re-opened, though?

**Comment by joshuap** [comment]
Yeah, reopening.

**Comment by butchler** [comment]
Hey there, just checking in. Any progress on this?

Right now we're using our own custom Honeybadger client that sends data to the API via POST, but I'd really like to just delete that code and go back to using the official client. However, I feel a little uncomfortable using this knowing that errors might silently fail to send if there's too much data in the context. The ability to detect if an error failed to send (https://github.com/honeybadger-io/honeybadger-js/issues/40) would also be enough to go back to using `honeybadger-js`.

**Comment by sljavi** [comment]
+1
this would be very useful for our team

**Comment by joshuap** [comment]
@butchler yep, this is something I'd like to tackle soon. I think it may require a pretty big overhaul of the current lib and probably deprecation of some of the older browser we support (it's probably time to drop IE6, right? 😀 )

I'm sorry I don't have an ETA yet, but I'll bump this up my priority list. I'm looking for some contract help if you guys know anyone with senior JS+OSS experience.

**Comment by joshuap** [comment]
This is currently on master and will be released in 1.0.0
