### ISSUE TITLE
notify breaks when context contains a Symbol

### ISSUE THREAD

**Issue by Munksey** [honeybadger-io/honeybadger-js#53]
The `serialize` method will handle a function properly, but does not work when there is a Symbol. 

Even though I am not having this problem personally, the method assumes that all the keys in the object are serializable, which is not necessarily true. Although, I am not sure what an elegant way of handling this is.

At the very least, it might be nice if honeybadger had some logic to send a generic error message if serializing the payload fails.

**Comment by joshuap** [comment]
@Munksey would you be able to provide a failing test case (or just an example) of how I can produce the error?

**Comment by Munksey** [comment]
You will need to run this on a modern browser. I am using the latest version of Chrome (v55) for Mac OS X (although I get this bug on Firefox, too). You can maybe add these tests to the testrunner.

```
    if (typeof Symbol === 'function') {
      it('handles symbols as values', function() {
        var sym = Symbol();

        Honeybadger.notify("testing", {
          context: {
            key: sym,
          }
        });

        afterNotify(function() {
          expect(requests.length).toEqual(1);
          expect(requests[0].url).toMatch('?');
        });
      });

      it('handles symbol as a key', function() {
        var sym = Symbol();
        var context = {};

        context[sym] = 'value';

        Honeybadger.notify("testing", { context: context });

        afterNotify(function() {
          expect(requests.length).toEqual(1);
          expect(requests[0].url).toMatch('?');
        });
      });
    }
```

The problem is that `serialize` cannot run `encodeURIComponent` on a Symbol, as they can't be cast to strings.

**Comment by joshuap** [comment]
@Munksey thanks!
