### ISSUE TITLE
[Ship.js] Don't create a release PR if there are no unreleased changes

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#530]
Links:

- [Our Ship.js config file](https://github.com/honeybadger-io/honeybadger-js/blob/master/ship.config.js)
- [Our Changelog file](https://github.com/honeybadger-io/honeybadger-js/blob/master/CHANGELOG.md)
- [Ship.js on GitHub](https://github.com/algolia/shipjs)
- [Ship.js docs](https://community.algolia.com/shipjs/guide/)

We have the [ship.js trigger](https://github.com/honeybadger-io/honeybadger-js/blob/master/.github/workflows/shipjs-schedule-prepare.yml) run the `npm run release` command once per week. Our [custom Ship.js config](https://github.com/honeybadger-io/honeybadger-js/blob/master/ship.config.js) is used to determine the next release version based on the unreleased section of our [changelog](https://github.com/honeybadger-io/honeybadger-js/blob/master/CHANGELOG.md). (Edit: see additional info about our Ship.js setup in the [readme](https://github.com/honeybadger-io/honeybadger-js#release-automation).)

Currently `npm run release` creates a PR even if there are no unreleased changes in the changelog. I want to skip those PRs—if there are no unreleased changes, then skip creating the PR. I'm not sure if this is [a configurable option](https://community.algolia.com/shipjs/reference/all-config.html#monorepo) w/ Ship.js; you might want to [ask the maintainers](https://github.com/algolia/shipjs/issues).

**Comment by incredimike** [comment]
Update: Looking into using the `shouldPrepare` callback to check if a release should be prepared. 
https://community.algolia.com/shipjs/reference/all-config.html#shouldprepare

Having some trouble testing it with --dry-run, since the dry run flag causes shipjs to bail on the preparation step BEFORE the shouldPrepare function has been called. I've modified the library for my own testing, and I'm reaching out to the ShipJS community to see if this should be adjusted in the library at large.

**Comment by joshuap** [comment]
It turns out the `shouldPrepare` approach didn't work because `commitNumbersPerType` is always 0 (since we're not using keep a changelog instead of conventional commits).

https://github.com/honeybadger-io/honeybadger-js/commit/37c6822b311ef3a6d12c54d97e08fc9b91e41115

**Comment by joshuap** [comment]
@shipjs prepare

(testing that revert.)

**Comment by shalvah** [comment]
I think https://github.com/honeybadger-io/honeybadger-js/pull/617 should fix it. Tested locally with dry run, but not sure how else to test.

**Comment by shalvah** [comment]
Okay, mentioned the bot, and nothing so far, so maybe...?🤔
