### ISSUE TITLE
ERR_INVALID_ARG_TYPE('listener', 'Function', listener); in Express JS

### ISSUE THREAD

**Issue by pankajjha-cd** [honeybadger-io/honeybadger-js#532]
## What are the steps to reproduce this issue?
1. Use [Express-Generator](https://expressjs.com/en/starter/generator.html) for Express Basic Setup 
2. Add Honeybadger [code](https://docs.honeybadger.io/lib/node.html#express-or-connect-framework) in [app.js](https://gist.github.com/pankajjha-cd/f7dffcdaa42f3921046e76236a1113f6) of the application
3. Throw a custom exception like `throw new Error('Exception message');` in any route response

## What happens?

When I hit the route, I get ERR_INVALID_ARG_TYPE and the execution of the server stops. The Application crashes.
I get following error
```
0|nodex  | events.js:111
0|nodex  |     throw new ERR_INVALID_ARG_TYPE('listener', 'Function', listener);
0|nodex  |     ^
0|nodex  | TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
0|nodex  |     at checkListener (events.js:111:11)
0|nodex  |     at ClientRequest.once (events.js:435:3)
0|nodex  |     at new ClientRequest (_http_client.js:202:10)
0|nodex  |     at Object.request (https.js:310:10)
0|nodex  |     at Object.request (/Users/pankajjha/development/node/node-projectx/node_modules/agent-base/patch-core.js:25:22)
0|nodex  |     at /Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:860:33
0|nodex  |     at fallback (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:708:16)
0|nodex  |     at getStats (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:684:5)
0|nodex  |     at Honeybadger.__send (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:849:9)
0|nodex  |     at Honeybadger.Client.notify (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:600:21) {
0|nodex  |   code: 'ERR_INVALID_ARG_TYPE'
0|nodex  | }
```

## What were you expecting to happen?
I was expecting the error gets logged 

## Any logs, error output, etc?
```
0|nodex  | events.js:111
0|nodex  |     throw new ERR_INVALID_ARG_TYPE('listener', 'Function', listener);
0|nodex  |     ^
0|nodex  | TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
0|nodex  |     at checkListener (events.js:111:11)
0|nodex  |     at ClientRequest.once (events.js:435:3)
0|nodex  |     at new ClientRequest (_http_client.js:202:10)
0|nodex  |     at Object.request (https.js:310:10)
0|nodex  |     at Object.request (/Users/pankajjha/development/node/node-projectx/node_modules/agent-base/patch-core.js:25:22)
0|nodex  |     at /Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:860:33
0|nodex  |     at fallback (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:708:16)
0|nodex  |     at getStats (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:684:5)
0|nodex  |     at Honeybadger.__send (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:849:9)
0|nodex  |     at Honeybadger.Client.notify (/Users/pankajjha/development/node/node-projectx/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:600:21) {
0|nodex  |   code: 'ERR_INVALID_ARG_TYPE'
0|nodex  | }
```

## Any other comments?

Tried adding the code in bin/www file as well but it doesn't work.

## What versions are you using?
**Operating System:** BigSur - MacOS
**Package Version:** ^3.0.3
**Browser Version:** Chrome Version 88.0.4324.146 | Postman Version 7.36.1 (7.36.1)
**Using any additional app:** PM2, Nodemon

**Comment by incredimike** [comment]
The stack trace points at `agent-base/patch-core.js`. [agent-base 4.3.0](https://github.com/TooTallNate/node-agent-base/tree/560f111674af84dec46a4c3070ddf3b22edd3e76) (released Jun 5, 2019) is the last version of the library to contain `patch-core.js`.

@pankajjha-cd Are your node_modules up to date? Please try updating `agent-base`. 

I cannot recreate the issue using [version 6.0.2](https://github.com/TooTallNate/node-agent-base/releases) or 4.3.0.

**Comment by pankajjha-cd** [comment]
Hi,
I removed my node_modules directory and moved `app.use(Honeybadger.errorHandler);` just before default error handler of express.js and it is working fine now.

only thing is that it is reporting 404 error as well to honeybadger and I couldn't find any doc to disable 404 error logging to honeybadger, may be you can help!

However, my original issue was resolved. Thanks to you.

**Comment by joshuap** [comment]
@pankajjha-cd I think you could ignore 404 errors using a `beforeNotify` handler:

https://docs.honeybadger.io/lib/javascript/guides/reducing-noise.html#ignoring-errors

Glad we could get this resolved! I'll close it now, but let me know if you need anything else.
