### ISSUE TITLE
right way to import types

### ISSUE THREAD

**Issue by Ali-Dalal** [honeybadger-io/honeybadger-js#538]
I am writing a wrapper for HB alert, I need to import types from HB so arguments and return type are typescript typed.

![image](https://user-images.githubusercontent.com/12471526/109105909-beb90500-7769-11eb-98c3-5bd1ee143007.png)

when I import the interfaces, it keeps saying 
`TS2305: Module '"../../node_modules/@honeybadger-io/js/honeybadger"' has no exported member 'Notice'.`

so my question is, are the interfaces exported? and what is the correct way to import the types
```ts
import { Notice} from '@honeybadger-io/js'; //gives error

// another try:
import * as Honeybadger from '@honeybadger-io/js';

export default function customAlert(message: string| Error, extra: Honeybadger.Notice){ // Honeybadger.Notice gives error
}
```

Thanks

**Comment by joshuap** [comment]
@Ali-Dalal our public types for the NPM package are [here](https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger.d.ts#L62). I'm not sure how to do what you're asking, to be honest. I've never tried that before (I'm not a TypeScript expert, unfortunately).

**Comment by mFingers** [comment]
@Ali-Dalal could you use [the beforeNotify hook](https://docs.honeybadger.io/lib/javascript/reference/configuration.html#beforenotify-handlers) to get the behavior you are looking for?

**Comment by JustFly1984** [comment]
Hello @joshuap  @mFingers I'm representing TheKnotWorldWide, as my client. We have similar issues, while migrating our API to TypeScript.

I've solved an import of the `Honeybadger.Notice` type in the project by using typescript's helper functions:

```typescript
Honeybadger.beforeNotify(
  (
    notice: Exclude<Parameters<typeof Honeybadger.notify>[0], globalThis.Error>
  ): false | void => {
    if (
      typeof notice !== 'string' &&
      typeof notice.context !== 'undefined' &&
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      notice.context.status === 401
    ) {
      return false
    }
  }
)
```

and still I had to use ts-ignore comment to continue working without introducing dirty hacks.

`d.ts` files are imperfect, and could be outdated sometimes, and could be incompatible with newer versions of typescript.

Currently I see a lot of errors in this package while typechecking the current working `typescript@4.2.4` project with `tsc --noEmit` and without --skipLibCheck flag, logs out a bunch of errors due to deprecation of implicit `any` type in favor of explicit `unknown` type:

```zsh
$ tsc --noEmit
node_modules/@honeybadger-io/js/honeybadger.d.ts:16:25 - error TS7006: Parameter 'req' implicitly has an 'any' type.

16   public requestHandler(req, res, next): void
                           ~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:16:30 - error TS7006: Parameter 'res' implicitly has an 'any' type.

16   public requestHandler(req, res, next): void
                                ~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:16:35 - error TS7006: Parameter 'next' implicitly has an 'any' type.

16   public requestHandler(req, res, next): void
                                     ~~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:17:23 - error TS7006: Parameter 'err' implicitly has an 'any' type.

17   public errorHandler(err, req, _res, next): unknown
                         ~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:17:28 - error TS7006: Parameter 'req' implicitly has an 'any' type.

17   public errorHandler(err, req, _res, next): unknown
                              ~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:17:33 - error TS7006: Parameter '_res' implicitly has an 'any' type.

17   public errorHandler(err, req, _res, next): unknown
                                   ~~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:17:39 - error TS7006: Parameter 'next' implicitly has an 'any' type.

17   public errorHandler(err, req, _res, next): unknown
                                         ~~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:18:24 - error TS7006: Parameter 'handler' implicitly has an 'any' type.

18   public lambdaHandler(handler): (event, context, callback) => void
                          ~~~~~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:18:35 - error TS7006: Parameter 'event' implicitly has an 'any' type.

18   public lambdaHandler(handler): (event, context, callback) => void
                                     ~~~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:18:42 - error TS7006: Parameter 'context' implicitly has an 'any' type.

18   public lambdaHandler(handler): (event, context, callback) => void
                                            ~~~~~~~

node_modules/@honeybadger-io/js/honeybadger.d.ts:18:51 - error TS7006: Parameter 'callback' implicitly has an 'any' type.

18   public lambdaHandler(handler): (event, context, callback) => void
                                                     ~~~~~~~~
```

<img width="570" alt="Screen Shot 2021-05-13 at 4 54 47 PM" src="https://user-images.githubusercontent.com/2255993/118110040-20554b00-b40c-11eb-8a03-93aa40c19341.png">


I'm myself maintainer of pretty successful open-source package written in typescript: https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/README.md

Would love to bring my expertise and provide help with refactoring JS and React API codebase to typescript.

As I see the correct approach would be to use `AWS` types from `@serverless/typescript` for lambda event, context and else.

**Comment by joshuap** [comment]
@JustFly1984 are you using the latest version of @honeybadger-io/js? We switched those definitions to use explicit any:

https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger.d.ts#L18

I'd accept a PR with the serverless `AWS` types if that is a better option.

**Comment by JustFly1984** [comment]
@joshuap Yes, I'm using latest version of the library. "@honeybadger-io/js": "3.2.0", and also I'm using typescript 4.2.4

Errors persists.

<img width="505" alt="Screen Shot 2021-05-18 at 4 13 27 AM" src="https://user-images.githubusercontent.com/2255993/118557482-6fdea280-b78f-11eb-8631-cfaa8e04d74f.png">

**Comment by joshuap** [comment]
@shipjs prepare

(Doh, I realized we have an unreleased change. Will have a new release to try shortly.)

**Comment by joshuap** [comment]
@JustFly1984 can you try 3.2.1 and see if you get the same errors?

**Comment by JustFly1984** [comment]
@joshuap Thank you, in 3.2.1 all errors are gone.

**Comment by joshuap** [comment]
@JustFly1984 awesome, thanks for the update!

**Comment by joshuap** [comment]
Closing this—hopefully, the latest release fixes everything. Feel free to reopen or create a new issue if not.
