### ISSUE TITLE
No TypeScript types for requestHandler or errorHandler

### ISSUE THREAD

**Issue by getabetterpic** [honeybadger-io/honeybadger-js#539]
## What are the steps to reproduce this issue?
1. Set up a new Node project using TypeScript (I'm using Nest)
2. Add `@honeybadger-io/js` to the project
3. Attempt to add `app.use(Honeybadger.requestHandler)`

## What happens?
TypeScript complains since there isn't a `requestHandler` or `errorHandler` type on the Honeybager export.

## What were you expecting to happen?
I should be able to use `Honeybadger.requestHandler` and `Honeybadger.errorHandler` without any TypeScript error.

## Any logs, error output, etc?
N/A

## Any other comments?
Here's a new Nest app illustrating this failure https://github.com/getabetterpic/honeybadger-not-working.

```
git clone git@github.com:getabetterpic/honeybadger-not-working.git
npm install
npm run start
```

Error:

```
yarn start
yarn run v1.23.0-20210103.1434
$ nest start
src/main.ts:12:23 - error TS2339: Property 'requestHandler' does not exist on type 'Honeybadger'.

12   app.use(Honeybadger.requestHandler);
                         ~~~~~~~~~~~~~~
src/main.ts:14:23 - error TS2339: Property 'errorHandler' does not exist on type 'Honeybadger'.

14   app.use(Honeybadger.errorHandler);
                         ~~~~~~~~~~~~

Found 2 error(s).

error Command failed with exit code 1.

```

## What versions are you using?
**Operating System:** macOS and Linux
**Package Version:** 3.0.3
**Browser Version:** N/A

**Comment by joshuap** [comment]
Fix released in 3.0.4
