### ISSUE TITLE
API Key security

### ISSUE THREAD

**Issue by snex** [honeybadger-io/honeybadger-js#54]
I have seen several issues here about the security of API keys in the javascript library, and it is being stated that this is just the nature of client side and we must accept that malicious users can steal our key and post errors to our Honeybadger app if they want.

I am sorry but this is simply not the case. There is no reason that API keys cannot be tied to the originating domain(s) specified by the user, or that auth tokens cannot be generated on the fly based on a key that it kept secretly. Please consider implementing something that does not just let anybody post to any Honeybadger that uses this library.

**Comment by joshuap** [comment]
@snex thanks for the suggestion. I'm not opposed to adding better API key security, but I don't want to just make it more difficult (but still possible, i.e. by spoofing the referer) to circumvent. Can you give me some examples of other open source libraries which solve this issue securely on the client-side?

**Comment by snex** [comment]
There are two ways I can think of at the moment:

1) Set CORS config on the honeybadger servers to only accept requests on behalf of the user. This would probably require a unique subdomain for each user, or some way to differentiate requests based on users. This way, the API key need not be secret. This method is susceptible to spoofing, as you mentioned.

2) Generate a token based on the secret key, and use that token as the authentication. This is how Amazon S3 allows direct uploads. Basically, the process would be as follows: The JS library first posts back to the home server, which generates a token based on the secret key and the data to be posted. The response comes back to the JS library, which then posts to Honeybadger using the token. The token is verified on Honeybadger based on the data and the secret key.

I have also seen Google use a client-id to verify AJAX calls, but to be honest I have no idea how they are authenticating it.

**Comment by joshuap** [comment]
Thanks for the explanation. I'm going to pass on this one for now; I don't see the benefit of adding extra hoops to jump through when it's still possible to circumvent since the secrets will always be client-side one way or another.
