### ISSUE TITLE
"Property 'hasOwnProperty' of object #<error> is not a function" reported in honeybadger

### ISSUE THREAD

**Issue by afgomez** [honeybadger-io/honeybadger-js#56]
While debugging our own Javascript exceptions I found one that I think might exists in honeybadger itself, or at least that's what honeybadger is telling me :)

All exceptions are coming from `Android Browser 4.0`.

![screen shot 2017-01-26 at 09 22 48](https://cloud.githubusercontent.com/assets/57448/22324354/0dda4116-e3a9-11e6-9e8c-5d85c00ecc67.png)

**Comment by joshuap** [comment]
@afgomez thanks, looks like you may be right. :) I'll see if I can reproduce this.

**Comment by afgomez** [comment]
Thanks a lot!

**Comment by janosch-x** [comment]
@joshuap FYI this still seems to be happening in honeybadger-js v0.5.5

![bildschirmfoto 2018-10-23 um 15 10 30](https://user-images.githubusercontent.com/10758879/47362983-0335c100-d6d6-11e8-9935-95cb14d0edac.png)

**Comment by joshuap** [comment]
@janosch-x hmmm, I think you're right; I'll reopen this issue until we get this fixed. Thanks!
