### ISSUE TITLE
Stop Honeybadger from Bubbling up in Console in Local Environment

### ISSUE THREAD

**Issue by tannerhuynh** [honeybadger-io/honeybadger-js#568]
## What are the steps to reproduce this issue?
1. Start react app in local environment
2. Cause a bug in the front end that would trigger HB

## What happens?
1. Multiple HB errors show up in console and all errors are wrapped in HB. Some stack trace are not clickable others are clickable. This is terrible for debugging because clicking on the links leads only to the HB call.
2. HB sends a report.

## What were you expecting to happen?
1. HB to not display in the console and instead only the react stack trace to be visible.
2. HB to NOT report in local environments. The documentation on the site clearly states that HB does not report to development environments by default, but our setup is still reporting.

## What versions are you using?
**Operating System: Mac Big Sur** 
**Browser Version: Chrome 88** …

[Example Image](https://ibb.co/L1qR17y)

**Comment by joshuap** [comment]
@tannerhuynh what version of honeybadger.js are you using? Make sure you are on the latest version of the @honeybadger-io/js package (currently 3.2.0), and that you are setting the `environment` config option as mentioned in [this guide](https://docs.honeybadger.io/lib/javascript/guides/environments-and-versions.html). It should be either "development" or "dev" for development environments. You can also explicitly disable reporting with the `reportData` option.

With that config in place, does Honeybadger still report in your local environment?

I'm not clear on what you mean by "errors are wrapped in HB." Can you elaborate on that?

**Comment by tannerhuynh** [comment]
Ah yes, we were using an outdated version that didn't seem to support what the new documentation had stated. The reporting issue is solved locally. However, we are still experiencing a double error in the console, one from HB and one from React. I was curious if the HB one can be silenced since the stack trace isn't helpful and is just noise.

[https://ibb.co/7pRQMjT](Example)

You can see the application chunk directs to where the error is actually located, whereas the HB stack trace is just noise.

**Comment by joshuap** [comment]
> However, we are still experiencing a double error in the console, one from HB and one from React. I was curious if the HB one can be silenced since the stack trace isn't helpful and is just noise.
> 
> https://ibb.co/7pRQMjT
> 
> You can see the application chunk directs to where the error is actually located, whereas the HB stack trace is just noise.

Does it say where that console message is being generated? Our react error boundary doesn't do any logging that I'm aware of, so I think that may be a feature of React. I'm not sure how we would disable that.

**Comment by tannerhuynh** [comment]
Here you see every message in the console is wrapped in this Honeybadger message leading back to the breadcrumb function. 

[https://ibb.co/Nx8Wd88](https://ibb.co/Nx8Wd88)

Specifically this line: 
[https://ibb.co/vPnz5zJ](https://ibb.co/vPnz5zJ)

Any idea what this is about?

**Comment by joshuap** [comment]
@tannerhuynh Gotcha. You can disable console breadcrumbs via Honeybadger's configuration:

https://docs.honeybadger.io/lib/javascript/guides/breadcrumbs.html#enablingdisabling-breadcrumbs

This isn't something that we do automatically, but I'll think about that a bit.

Also, for future reference, [you can upload file attachments to issues on GitHub directly](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests). I won't be clicking on any future ibb.co links because the advertisements are gross. :)

**Comment by tannerhuynh** [comment]
Hah, I didn't know that. Thanks!
