### ISSUE TITLE
Better grouping of errors in single page applications

### ISSUE THREAD

**Issue by butchler** [honeybadger-io/honeybadger-js#59]
NOTE: I think this is really an issue with the Honeybadger backend/UI and not the `honeybadger-js` client, so this is probably not the right place for this. However, it is something that probably only affects JavaScript single page applications. Please let me know if there is a more appropriate place for this.

According to http://docs.honeybadger.io/guides/api.html#sample-payload, Honeybadger uses the backtrace to group errors together in the Honeybadger UI:

> The backtrace key of the error hash is essential, as that is used for grouping similar errors together in the Honeybadger UI.

When we deploy our frontend code, we generate a completely new minified bundle file with Webpack every time. This means that the line and column numbers in the stack trace for errors thrown are very likely to be slightly different after each deploy, even if the relevant line/module in the original source code was not changed at all.

This means that after every deploy, the same errors that were being reported to Honeybadger before the deploy are considered to be new errors, and they are not grouped together in the UI. This makes it more difficult to determine if error reports we receive after a deploy are caused by the deploy or are just new instances of existing issues. This also means we can't really use the "ignore" feature because every error we ignore will effectively become unignored after the next deploy.

Of course the best solution would be to just fix all of our errors, but it takes time and it would be nice if Honeybadger would stop badgering us about the same old errors in the mean time. =P

I'm not sure what the best way to solve this would be, but here are some ideas I came up with:

* Continue to group errors by stack trace, but use the *source-mapped* stack trace if a JavaScript source map is provided. (This might mean that Honeybadger would have to not show an error report in the UI until it has finished the source mapping operation, though.)
* Add the ability to "group by" various options in the Honeybadger UI. For example, "Group by stack trace" (default), "Group by source-mapped stack trace" (probably only applies to JavaScript), "Group by name", "Group by message", etc.

**Comment by joshuap** [comment]
Hi @butchler, thanks for the detailed post. I am working to address this issue in the next version of our source map feature. My goal is to eventually implement the first idea you mentioned -- add an option to use the source mapped stack trace for grouping. This will require some reworking of our pipeline, and that's dependent on some changes to the current source map feature which I'm currently working on.

**Comment by crazysaem** [comment]
Hi @joshuap 
Will this issue be solved with the "New Error Grouping" feature, announced in this blog post [http://blog.honeybadger.io/source-map-upload/](http://blog.honeybadger.io/source-map-upload/)?

**Comment by joshuap** [comment]
Yes, it should! Could you try upgrading to v0.5.0 and see if the grouping is better using the source map?
