### ISSUE TITLE
Filter/Ignore certain errors?

### ISSUE THREAD

**Issue by i8ramin** [honeybadger-io/honeybadger-js#6]
The Ruby client of honeybadger allows you to filter/ignore certain errors, but I could not find the same option in the JS client. Is this possible somehow? I wanted to ask before I cloned the repo and started to add the functionality myself as a pull request.

Thanks

**Comment by henrik** [comment]
Because Google landed me here – this is how to do it: https://docs.honeybadger.io/lib/javascript/guides/reducing-noise/#ignoring-errors
