### ISSUE TITLE
"Can't execute code from a freed script" on IE and Edge browsers

### ISSUE THREAD

**Issue by mockdeep** [honeybadger-io/honeybadger-js#62]
It's unclear whether this is caused by Honeybadger or Honeybadger is just the messenger, but we've been seeing a lot of errors from IE and Edge browsers recently:

```
Can't execute code from a freed script
```

As near as I can tell it looks like it's coming from [here](https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger.js#L363), when it calls `return fn.apply(this, arguments);`. Any idea what might be going on with this? From what searching I've done, it looks like it's related to code trying to execute from another frame that has since been removed. We don't do anything with frames in our code, so trying to figure out where it is coming from.

**Comment by joshuap** [comment]
@mockdeep not sure -- I haven't seen this before. I'm happy to try to reproduce it, though. Have you been able to reproduce yourself at all? It would be helpful to have a snippet that I could run in IE/Edge.

**Comment by mockdeep** [comment]
@joshuap no, it's a pretty vague error and doesn't happen consistently. I think we can go ahead and close this. I suspect things like this have more to do with the user clicking around the page quickly or closing a browser tab while the page is loading. Thanks for getting back to me.
