### ISSUE TITLE
TypeScript issue w/ React

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#633]
Here's an issue reported via email. I wonder if there's a TS definition bug in [honeybadger-react](https://github.com/honeybadger-io/honeybadger-react) related to the recent TS fixes in honeybadger-js?

> I'm currently working on updating typescript and other dependencies in next.js app, and I have found an issue with your package. I'm using the latest 3.2.4 version as it is described in https://docs.honeybadger.io/lib/javascript/integration/react/
>
> The issue is that const honeybadger = Honeybadger.configure(config) returns type `Client`, but <ErrorBoundary honeybadger={honeybadger}> component expects different type and produces an error message: 
>
> ```
> No overload matches this call.
>   Overload 1 of 2, '(props: Props | Readonly<Props>): ErrorBoundary', gave the following error.
>     Type 'Client' is not assignable to type 'Honeybadger'.
>       Type 'Client' is missing the following properties from type 'Honeybadger': errorHandler, requestHandler, lambdaHandler
>   Overload 2 of 2, '(props: Props, context: any): ErrorBoundary', gave the following error.
>     Type 'Client' is not assignable to type 'Honeybadger'.
>       Type 'Client' is not assignable to type 'Honeybadger'.ts(2769)
> honeybadger-react.d.ts(6, 5): The expected type comes from property 'honeybadger' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<ErrorBoundary> & Readonly<Props> & Readonly<{ ...; }>'
> honeybadger-react.d.ts(6, 5): The expected type comes from property 'honeybadger'
> ```

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3k76p)

**Comment by joshuap** [comment]
@subzero10 can you take a look at this and #634 when you get the chance?

**Comment by subzero10** [comment]
> @subzero10 can you take a look at this and #634 when you get the chance?

Yes! Will do!

**Comment by subzero10** [comment]
@joshuap Regarding this ticket, please my [PR](https://github.com/honeybadger-io/honeybadger-react/pull/272) on `honeybadger-react`.

**Comment by joshuap** [comment]
I released the fix for this in  @honeybadger-io/react 1.0.2
