### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'enter')

### ISSUE THREAD

**Issue by justinlittman** [honeybadger-io/honeybadger-js#634]
## What are the steps to reproduce this issue?
1. Checkout this branch: https://github.com/LD4P/sinopia_api/tree/t156-openapi
2. `npm i`
3. `npm run test`
4. In `app.js` put HB before OpenApiValidator:
```
// Use HB before all other app middleware.
Honeybadger.configure({
  apiKey: process.env.HONEYBADGER_API_KEY
})
app.use(Honeybadger.requestHandler)

app.use(
  OpenApiValidator.middleware({
    apiSpec: './openapi.yml',
    // validateResponses: true, // <-- to validate responses
  }),
)
```
5. `npm run test`

## What happens?
Tests run successfully when OpenApiValidator is first (any errors are OK; the implementation isn't complete); tests die when HB is first.

## What were you expecting to happen?
Tests should run.

## Any logs, error output, etc?
```
TypeError: Cannot read properties of undefined (reading 'enter')
    at AsyncHook.before (node:domain:97:20)
    at emitHook (node:internal/async_hooks:237:38)
    at emitBeforeScript (node:internal/async_hooks:503:5)
    at promiseBeforeHook (node:internal/async_hooks:347:3)
```

## What versions are you using?
**Operating System:** OS X 11.5.2
**Package Version:** 3.2.4
```
$ node -v
v16.9.0
$ npm -v
7.21.1
```

**Comment by subzero10** [comment]
Hey @justinlittman,

This link is not valid anymore: https://github.com/LD4P/sinopia_api/tree/t156-openapi

Did you manage to solve this?

I created a fresh project, found [here](https://github.com/subzero10/honeybadger-open-api-test).
I deliberately make the Open Api Validator fail by returning a non-matching json for the `/users` route:
![image](https://user-images.githubusercontent.com/5813382/133880185-3be148f4-54fd-4b8a-8e2f-f5aa57e6bff3.png)

The tests run and fail as expected 🤷‍♂️ 
Can you please share some code to investigate this further? Or recover the branch above?

Also, @joshuap, I have a question:
Should we notify honeybadger while running the tests? See below screenshot:
![image](https://user-images.githubusercontent.com/5813382/133880394-63a0c4aa-8090-4058-bead-58d3b2728333.png)
We could check the `NODE_ENV` or identify if mocha or jest (or any other test framework) is running and automatically disable sending errors to Honeybadger.
FYI, a 403 message is shown if the API key is not set.
![image](https://user-images.githubusercontent.com/5813382/133880534-a04b012d-3c39-45e4-9974-028c043dc0ba.png)

What do you think?

**Comment by joshuap** [comment]
> Also, @joshuap, I have a question:
> Should we notify honeybadger while running the tests? See below screenshot:
> ![image](https://user-images.githubusercontent.com/5813382/133880394-63a0c4aa-8090-4058-bead-58d3b2728333.png)
> We could check the `NODE_ENV` or identify if mocha or jest (or any other test framework) is running and automatically disable sending errors to Honeybadger.
> Also, another screenshot with a 403 message shown if the API key is not set (which is the expected).
> ![image](https://user-images.githubusercontent.com/5813382/133880534-a04b012d-3c39-45e4-9974-028c043dc0ba.png)
> 
> What do you think?

We have the `developmentEnvironments` options which automatically include the "test" environment—so if the Honeybadger `environment` === "test", errors should not be reported. If you want to prevent the API key warning in test environments, you could shift the order of [these conditionals](https://github.com/honeybadger-io/honeybadger-js/blob/master/src/core/client.ts#L133).

**Comment by subzero10** [comment]
@joshuap That's nice, I missed those! I guess we could switch the conditionals and if `disabled: true` or `reportData: false`, we could exit the `notify` function. I will submit a PR!

**Comment by subzero10** [comment]
Link to [PR](https://github.com/honeybadger-io/honeybadger-js/pull/637).
