### ISSUE TITLE
Should the `enableUncaught` config option apply to all instrumentation?

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#635]
Currently, the `enableUncaught` option disables reporting errors caught by `window.onerror`,  but there are a few other places we automatically report errors:

1. [timers plugin](https://github.com/honeybadger-io/honeybadger-js/blob/master/src/browser/integrations/timers.ts)
2. [event_listeners plugin](https://github.com/honeybadger-io/honeybadger-js/blob/master/src/browser/integrations/event_listeners.ts)

Both of those plugins use the [`__wrap` function](https://github.com/honeybadger-io/honeybadger-js/blob/4e00f2b158182929c7aac745dedbbcccaa73fb60/src/browser.ts#L134) to automatically report errors in callbacks. Currently when `window.onerror` is disabled, `try/catch` is used instead (warning: the logic in `__wrap` is fairly complex).

Recently a customer reported an issue where they are using honeybadger.js in a third-party chat widget that will be installed in many different host applications, so they disabled `enableUncaught` so that they could report errors in their widget by intentionally calling `Honeybadger.notify`. They were confused when an unrelated error was reported in an event listener.

Does it make sense to expand the meaning of `enableUncaught` to apply to *all* automatically reported errors?

**Comment by joshuap** [comment]
Follow-up question: if `enableUncaught` disables *reporting* uncaught errors, should breadcrumbs still be recorded when the uncaught errors happen? That would mean that the instrumentation should still run (so that breadcrumbs are added for uncaught errors), but `enableUncaught` would control whether `Honeybadger.notify` is called for uncaught errors.

**Comment by subzero10** [comment]
Hello, here's what I'm thinking on this matter:

- A customer that uses `enableUncaught` most probably wants to call notify _manually_. This means we should not report errors _automatically_.
- We also have the option `enableUnhandledRejection`. Perhaps we could have `enableTimerErrors` and `enableEventListenerErrors`. Though I believe these options fall under the `enableUncaught` option and they would be confusing for customers.

As per the follow-up question, we could keep the breadcrumbs for uncaught errors, since they are easily identified in the _Breadcrumbs_ tab. Another possibility would be to add another option in breadcrumbs configuration, so we offer the option to disable that functionality also:
```
Honeybadger.configure({
  breadcrumbsEnabled: {
    dom: true,
    network: true,
    navigation: true,
    console: true,
    uncaught: true
  }
})
```

**Comment by joshuap** [comment]
Thanks @subzero10!

> A customer that uses `enableUncaught` most probably wants to call notify manually. This means we should not report errors automatically.

I agree—I think we should apply this option to the timers and event_listener plugins.

> We also have the option `enableUnhandledRejection`. Perhaps we could have `enableTimerErrors` and `enableEventListenerErrors`. Though I believe these options fall under the `enableUncaught` option and they would be confusing for customers.

Right, let's not add additional options. Although, I think it's OK that `enableUnhandledRejection` is a separate option since promise rejections seem a bit different from other types of uncaught errors. Does that make sense to you?

> As per the follow-up question, we could keep the breadcrumbs for uncaught errors, since they are easily identified in the _Breadcrumbs_ tab. Another possibility would be to add another option in breadcrumbs configuration, so we offer the option to disable that functionality also:
> ```
> Honeybadger.configure({
>   breadcrumbsEnabled: {
>     dom: true,
>     network: true,
>     navigation: true,
>     console: true,
>     uncaught: true
>   }
> })
> ```

I don't think this is necessary—let's continue to collect breadcrumbs for all unhandled errors as well as promise rejections.

**Comment by subzero10** [comment]
@joshuap I'm following the comments and I want to make sure I got this right:
```
const onErrorEnabled = client.config.enableUncaught
// Catch if:
//   1. We explicitly want to catch (i.e. if the error could be
//      caught before reaching window.onerror)
//   2. The browser provides less information via the window.onerror
//      handler
//   3. The window.onerror handler is unavailable
if (opts.catch || preferCatch || !onErrorEnabled) {
    // call func with try catch
}
```
The `if` block will execute if:
- `opts.catch` is true **OR**
- `preferCatch` evaluates to true (based on browser) **OR**
- `enableUncaught` **is** false

Do we want to change that to:
- `enableUncaught` is true **AND**
- (
    - `preferCatch` evaluates to true (based on browser) **OR**
    - `opts.catch` is true
 )

What if `enableUncaught` is true and both `preferCatch` and `opts.catch` evaluate to `false` ? Do we expect the window.onerror handler to kick in if an error occurs? Or should we do something like this:
- `enableUncaught` is true **AND**
- (
    - `enableUncaught` is true **OR**
    - `preferCatch` evaluates to true (based on browser) **OR**
    - `opts.catch` is true
)

**Comment by joshuap** [comment]
> > I agree—I think we should apply this option to the timers and event_listener plugins.
> 
> Should I take this ticket and do it?

Let's hold for now until I can spend some time looking at it. I'll walk you through the conditional logic in your last comment and take a closer look at the code myself, as this is probably the most complex part of the library.
