### ISSUE TITLE
Add an automated release task

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#64]
This is just another script that will eventually live in *bin/*.

**Comment by monde** [comment]
@joshuap this should be the like npm bump script in honeybadger-js ?
 https://github.com/honeybadger-io/honeybadger-js/blob/master/package.json#L21

this is how I wired the prepublish hook in honeybadger-webpack
https://github.com/honeybadger-io/honeybadger-webpack/blob/master/package.json#L13

**Comment by joshuap** [comment]
We could do something similar with the prepublish hook, if it makes sense given that we also need to push the release files in /build/v* to S3.

This is the manual process I do when cutting a new release:

1. Update the versions and CHANGELOG. I use `npm run bump` if it's a patch release, otherwise I manually update the versions (similar to what [bin/bump](https://github.com/honeybadger-io/honeybadger-js/blob/master/bin/bump) does). I.e., the version is updated from 1.2.2 to "1.2.3".
2. Commit with the message "Release v1.2.3"
3. Run `git --tag v1.2.3`
4. Push to GitHub: `git push --tags origin master`
5. Publish npm package: `npm publish`
6. Build release files to *build/v1.2.3/*: `make`
7. Sync *build/v1.2.3/** to *s3://bucket-for-honeybadger-js/v1.2/**
8. Invalidate cloudfront distribution with the following pattern: "/v1.2/*".

I envision this all going into a new script in `bin/` which we can run via a command such as `npm run release`. See also #65, which would also move the steps to build the release that are currently in a Makefile to an NPM script in bin/.

**Comment by joshuap** [comment]
Oh btw, currently uglify JS v2 must be used for `make` to work: `npm install -g uglify-js@2`

**Comment by joshuap** [comment]
Closed in https://github.com/honeybadger-io/honeybadger-js/commit/14c0020926b551b6ada36f6b6bbec44211e6438e
