### ISSUE TITLE
Unable to get an error thrown from inside the handler after wrapping it in lambdaHandler

### ISSUE THREAD

**Issue by tweaktastic** [honeybadger-io/honeybadger-js#648]
## What are the steps to reproduce this issue?
1. Create an APIGateway handler method for AWS lambda
2. Throw an error inside the handler.
3. Add a test to execute the handler to throw an error. The error never gets thrown.

I have my main handler as defined below:
```
import { APIGatewayProxyHandler } from 'aws-lambda';
import Honeybadger from '@honeybadger-io/js';
const handler: APIGatewayProxyHandler = async(event, context) => {
	//performs some logic or throw an error
	try { // blah } 
	catch(err) { throw new Error('Some Error); }
}

export default Honeybadger.lambdaHandler(handler);
```

In my tests I import this handler and want the test to fail

```
import handler form '../index.ts';
describe('Handler', () => {
  test('Error is handled', async () => {
      try { 
        // valid event and context are manually added fixtures
         await handler(validEvent, context);
         throw new Error('handler should throw an error');
      } catch(err) {
         expect((<Error>e).message).toBe('Some Error');
      }
  });
});
```

## What happens?
There are two things that are happening wrong.
- The handler code doesn't get executed synchronously during the tests. Any `console.log` that I add to the handler show up after the test has ended. I am using `Jest` for testing.
- The handler never throws the error as is being expected due to it being executed in an async manner.

## What were you expecting to happen?
I was expecting that my handlers and tests keep on working as they were before I started wrapping them in `lambdaHandler`.

## Any logs, error output, etc?
As stated above, the code works in an async manner. I see logs after the test has ended. The `await` doesn't seem to work.

## Any other comments?
It looks like the wrapper is not using `Promise`. It expects a callback to be passed to it to which is passes the `error` in case and error is produced. Please correct me if my understanding is wrong.

## What versions are you using?
**Operating System: Mac OS Big Sur 11.4 (20F71)** …
**Package Version: `"@honeybadger-io/js": "^3.2.5"`** …
**Browser Version: Node 14, Typescript, "aws-lambda": "^1.0.6"** …

**Comment by tweaktastic** [comment]
Hi @subzero10 Thanks for the update regarding this. I tried to make this work as per your example that you posted yesterday itself.
```
import handler from './index';
describe('Handler', () => {
    test('Error is handled', (done) => {
        handler({}, {}, (err?: Error, resp?: any) => {
            if (!err) {
                done(new Error('should not reach here'))
                return
            }
            expect(err?.message).toBe('Some Error')
            done()
        });
    });
});
```
I have been trying to make it work since yesterday but the test times out without ever entering the callback. I am using jest and am wondering if I am doing something wrong.

```
import handler from './index';
describe('Handler', () => {
    test('Error is handled', (done) => {
        handler(validEvent, context, (err?: Error, resp?: any) => {
          console.log('gets executed');
          done();
        });
   });
});
```

**Comment by tweaktastic** [comment]
@subzero10 I have added a sample repo here. https://github.com/tweaktastic/honeybadger-testing

**Comment by subzero10** [comment]
Hey @tweaktastic,
Thank you for creating a repo. I have found the issue and submitted a [PR here](https://github.com/honeybadger-io/honeybadger-js/pull/650).
It seems that the callback is not called if some preconditions fail and one of them is _missing api key_.
As a workaround (for your tests to pass and until the PR is merged), you can add this block of code just before `Honeybadger.lambdaHandler()`:
```
Honeybadger.configure({
  apiKey: 'test'
})
```
In any case, you will have to supply an `apiKey` to use this on production, you just have to make sure you provide one for the tests (any string will do for the tests).

**Comment by subzero10** [comment]
I understand. `reportData` is actually one of the preconditions I mentioned above. That's why it behaves the same as not supplying an `apiKey`.

You are correct, my PR should call the callback even when `reportData` is `false`.

**Comment by tweaktastic** [comment]
Thanks for all your help @subzero10. I really appreciate your feedback and your quick response regarding this. We will wrap the handler to return the Promise as you have mentioned.  Looking forward to use `Honeybadger` alerting.

**Comment by joshuap** [comment]
This is released in 3.2.7. Let me know if you need anything else!

**Comment by tweaktastic** [comment]
@subzero10 Hope you are doing well. We integrated your changes to our project and the error now do get reported however there are multiple issues that we are facing.

- We were earlier using `notify` to report errors. This doesn't work with Lambdas as they exit even before the lib has made a call to honeybadger. This we were getting only fraction of errors getting reported to use and thus started exploring `lambdaHandler`. Now the issues is, with `notify` we could add context to be reported to the `honeybadger` console. This enabled us to add custom trace ids and other details we needed to debug issues. But it looks like when we use `lambdaHandlers` nothing of that gets reported. Is there a way to add custom fields to be reported using `lambdaHandler`?
- Secondly, I think this is the way lambdaHandler was deigned and it didn't occur to me before. The only time an error gets reported to `honeybadger` is when an error is thrown from inside the main handler. However, we have some use cases where we return error to the caller (`400`, `403`, `401`, `429`). We don't raise an error but rather send a response back. In this case we would like to report an alarm but it doesn't seem possible with `lambdaHandler`.

Please let us know how we can achieve the above two things? I tried doing this in our project to `await` the `notify` call.
```
const promisifiedNotify = promisify(Honeybadger.notify).bind(Honeybadger);
```
Awaiting the above method does ensure that error gets reported but it does come with an increased execution times as it actually waits for `http` call to get completed. Any help would be greatly appreciated. Thank you!

**Comment by subzero10** [comment]
Hey @tweaktastic, I'm glad to see that you are finally getting errors reported on _Honeybadger_.

> We were earlier using notify to report errors. This doesn't work with Lambdas as they exit even before the lib has made a call to honeybadger. With this we were getting only fraction of errors getting reported to us and thus started exploring lambdaHandler. Now the issue is, with notify we could add context to be reported to the honeybadger console. This enabled us to add custom trace ids and other details we needed to debug issues. But it looks like when we use lambdaHandlers nothing of that sort can get reported. Is there a way to add custom fields to be reported using lambdaHandler?

Have you looked into the `beforeNotify` handler? That could help achieve what you want. I'm not 100% sure though, since I haven't read your source code. But it may be possible if you register some callbacks to be called in the `beforeNotify` handler.  The callback is called with a `Notice` object with a `context` property that you can use to add custom data. 

> Secondly, I think this is the way lambdaHandler was deigned and it didn't occur to me before. The only time an error gets reported to honeybadger is when an error is thrown from inside the main handler. However, we have some use cases where we return error to the caller (400, 403, 401, 429). We don't raise an error but rather send a response back. In this case we would like to report an alarm but it doesn't seem possible with lambdaHandler.

We may be able to add an option for that to happen automatically or see if we can come up with a workaround. Can you clarify what you mean with the phrase `report an alarm`? Personally, I think error codes similar to `400`, `401`, `403` and `429` should not be reported to your error monitoring tool but to your logging service (i.e. Cloudwatch), but I will look into that nevertheless.

> Awaiting the above method does ensure that error gets reported but it does come with an increased execution times as it actually waits for http call to get completed.

Can you please confirm that the increased execution times refer to the time for the client to receive the response and not the lambda function execution time? Because it would make sense for the lambda function to have increased execution time (since it has to wait for the http request to complete), but ideally it should happen after the response is sent to the client.
