### ISSUE TITLE
`afterNotify` handlers should be called even if notice is not sent to honeybadger

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#654]
`afterNotify` handlers are not called if preconditions fail. We can call them and pass on an `error` as the first parameter.
Example: `new Error('API key is not configured')`

More on this [here](https://github.com/honeybadger-io/honeybadger-js/pull/650#issuecomment-956787935).

Note to self:
~- Should this be a major version release? What if there are users that rely on `afterNotify` as an indication that the error was indeed reported on Honeybadger? 🤔~

**Comment by joshuap** [comment]
> * Should this be a major version release? What if there are users that rely on `afterNotify` as an indication that the error was indeed reported on Honeybadger? 🤔

I kind of doubt this, but even if they are, they *should* be handling the error argument already (since the error report can fail in other ways).
