### ISSUE TITLE
Logging errors in development mode

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#661]
Some users want to log errors rather than report them in development mode. Currently [we do `console.debug`](https://github.com/honeybadger-io/honeybadger-js/blob/3d9312daaf7c570888cbf53c8c435e9a42d595b1/src/core/client.ts#L146) when skipping errors in development mode, but we don't include the original error in the output, and the `debug` level is easy to miss because it's usually suppressed by default.

Should we be logging the original error, i.e. with a `console.error` call? Fwiw, I'm not totally sure myself, because uncaught errors do appear in the console as far as I know. 

Another option could be to let users do their own logging with a `beforeNotify`/`afterNotfiy` handler (now that we're changing these callbacks to always run).

OR, we could add the error object to the current logging, and then improve the docs so that people realize they can enable debug logs to see more output.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3sie9)

**Comment by joshuap** [comment]
What do you think @subzero10?

**Comment by subzero10** [comment]
In my experience with the npm space, packages hide their _debug_ logs by default.
I think we could use the [debug](https://www.npmjs.com/package/debug) module to log all our _debug_ messages and make sure to include in our documentation how to enable them (simply set an env variable).
For example, [here](https://expressjs.com/en/guide/debugging.html) is how it is documented for express.js.
We could also take this a step further and [style the errors](https://github.com/AriaMinaei/pretty-error).

**Comment by joshuap** [comment]
We do have an additional `debug` config option already:

https://docs.honeybadger.io/lib/javascript/reference/configuration/#configuration-options

Basically that enables additional debug logging to the logger, but you may also need to enable the debug level in the console to see them in some browsers? It's been a while since I used it.

In any case, the debug output does not currently include the notice/error. Something like this might be enough:

```
this.logger.warn('Dropping notice: honeybadger.js is in development mode', notice)
```

**Comment by joshuap** [comment]
Related—someone else just requested a similar feature, but in production:

> Hi, is there any way to enable errors still being displayed in the console in production? I want to catch everything and send it to honeybadger but also let it log out as an error in the browser console too.

That might be a separate issue, but dropping it here for now. I wonder if we should always log the error when `Honeybadger.notify` is called?

**Comment by subzero10** [comment]
> Related—someone else just requested a similar feature, but in production:
> 
> > Hi, is there any way to enable errors still being displayed in the console in production? I want to catch everything and send it to honeybadger but also let it log out as an error in the browser console too.
> 
> That might be a separate issue, but dropping it here for now. I wonder if we should always log the error when `Honeybadger.notify` is called?

That might be a good idea. As a user, I would like to have this.

**Comment by joshuap** [comment]
I'm working on this now. I think I've changed my mind about making the production mode more verbose, but I should be able to improve the debug and development mode logging.
