### ISSUE TITLE
AWS Lambda Integration: async handler

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#677]
### Discussed in https://github.com/honeybadger-io/honeybadger-js/discussions/674

Improve implementation of callback based and async (promise based) lambda handlers.

- Modify lambdaHandler to return async handler instead of callback based handler.

Question: Should this be a major release?

**Comment by shalvah** [comment]
> Should this be a major release?

By itself, hopefully not. But if we go ahead to replace the callback code with promises, then perhaps.

**Comment by subzero10** [comment]
> > Should this be a major release?
> 
> By itself, hopefully not. But if we go ahead to replace all the callback code in the package with promises, then perhaps.

We are not replacing all code with promises in this PR but we are going to be returning a promise-based lambda handler instead of callback-based.

**Comment by subzero10** [comment]
This has been released with v4 (currently in beta).
