### ISSUE TITLE
Codebase: Callback to Promise based

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#678]
### Discussed in https://github.com/honeybadger-io/honeybadger-js/discussions/674

Replace callbacks with promises in the package.
Consider using a [polyfill](https://github.com/rollup/plugins/tree/master/packages/inject) to support Promises for browsers that do not support it.

**Comment by joshuap** [comment]
I think I'm still not totally clear on how much effort this would take, and if it would introduce any breaking changes for end-users. The primary benefit is that it would simplify the internal code, right?

**Comment by subzero10** [comment]
**Effort:**
It should be easy to do. After a quick look through the code, we'd have to modify only a few places in code:
- `server.util.getStats`
- `server.util.getSourceFile`
- `core.util.getSourceForBacktrace`
- `lambdaHandler` -> although it's tackled in a different issue/PR.

Then, make sure to include a [polyfill](https://github.com/rollup/plugins/tree/master/packages/inject) for the browser client.

**Breaking Changes:**
We are modifying internal code, so I don't see any.

**Benefit:**
Simplify and modernize the code. Promises replaced [callbacks](http://callbackhell.com).
