### ISSUE TITLE
AWS Lambda integration: Add timeout warning

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#679]
### Discussed in https://github.com/honeybadger-io/honeybadger-js/discussions/674

Add a timeout warning when the lambda function is within a number of milliseconds from tis execution time (15 minutes).

**Comment by shalvah** [comment]
Just to add: it's not necessarily 15 minutes. We should use [`context.getRemainingTimeInMillis()`](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html) to fetch the remaining time.
