### ISSUE TITLE
'prototype' is undefined

### ISSUE THREAD

**Issue by HolixSF** [honeybadger-io/honeybadger-js#68]
In the event targets snippet from `bugsnag` im receiving an error where prototype is undefined.
```javascript
prototype = window[prop] && window[prop].prototype;
```
im using webpack to bundle and might be running into an issue with transforming es2015 modules

**Comment by HolixSF** [comment]
looks like theres a couple of undeclared variables in this snippet

**Comment by joshuap** [comment]
@HolixSF thanks! b48a28ac40d5a098aaf42f5d75b113332aca6225 should fix this. Feel free to download/test it. I'm shooting for a new release by Thursday.
