### ISSUE TITLE
Notifications still sent even when environment is development

### ISSUE THREAD

**Issue by novito** [honeybadger-io/honeybadger-js#71]
# Problem

Even when Honeybadger is configured with environment being 'development', the notifications are being sent. This doesn't happen with the Ruby library.

# Expected behavior

By default don't notify if environment is 'development'

**Comment by joshuap** [comment]
@novito I agree that this would be a nice feature to have parity with the Ruby library. The way I'd do it is to add a `developmentEnvironments` config option which defaults to `['development', 'test']`, and then halt notifications if the current `environment` setting is in that list. The check should happen in the same place that we check the `disabled` option (which may change in #72).

**Comment by nenadjaja** [comment]
It would be great to have this working, so we won't get too much noise in our logs. Thanks!
