### ISSUE TITLE
non-idempotent wrap() can interfere with sites

### ISSUE THREAD

**Issue by bddean** [honeybadger-io/honeybadger-js#75]
In the client script, `wrap(wrap(fn))` should be the same as `wrap(fn)`. Currently using an object as a listener to multiple events causes Honeybadger to wrap the object's handleEvent() that many times.

In [this MutationObserver shim](https://github.com/Polymer/MutationObservers/blob/master/MutationObserver.js), a Registration  object can add itself as an event listener every time a node is removed from the DOM. Honeybadger wraps the Registration's handleEvent property until calls start to exceed the stack size limit and, on IE11 at least, the browser freezes.

I think adding the line `fn.___hb.___hb = fn.___hb` after [this line](https://github.com/honeybadger-io/honeybadger-js/blob/master/honeybadger.js#L387) would do the trick

**Comment by joshuap** [comment]
Thanks @bddean! It sounds like you're on to something here. I'm planning to look into it in depth tomorrow.

**Comment by joshuap** [comment]
@bddean I added your suggested fix in 9f8d309e5406d860fb2ebe8b402877da48dc80f4. I verified that my test failed before adding your fix. Does that look right to you? If so, I'll merge and release in v5.0.1.

**Comment by bddean** [comment]
@joshuap Lgtm! Thanks!
