### ISSUE TITLE
ignorePatterns feature should be removed from documentation

### ISSUE THREAD

**Issue by hislopzach** [honeybadger-io/honeybadger-js#805]
## What are the steps to reproduce this issue?
1. https://docs.honeybadger.io/lib/javascript/support/faq/ suggests that one can ignore errors through the use of the `ignorePatterns` config option
2. [this commit](https://github.com/honeybadger-io/honeybadger-js/commit/4d5f1f966a1853f1534a0de217acd8cac32dbf45) (4d5f1f) shows that the option has been removed.[ the upgrade to v3](https://docs.honeybadger.io/lib/javascript/support/upgrading-to-v3/) page also lists the removal of this prop

## What happens?
I tried to use a deprecated option, so it didn't work

## What were you expecting to happen?
documentation should not contain removed/deprecated options

**Comment by joshuap** [comment]
You're right, thanks! This has been fixed.
