### ISSUE TITLE
honeybadger.configure callback

### ISSUE THREAD

**Issue by erichulburd** [honeybadger-io/honeybadger-js#81]
I noticed some behavior where initial render of my application did not log any errors to honeybadger. However, if the error occurs after some UI event (such as a click or change), the error is logged successfully (I am using the default window `onerror` event behavior).

Is there a callback or should I set a timeout to make sure that Honeybadger is configured before rendering my app?

**Comment by joshuap** [comment]
@erichulburd we do support sending errors that occur before the page is fully loaded, however you must configure your API key directly after including honeybadger.js (so require honeybager, and then configure immediately). Or you could configure the API key using the data attribute:

```html
<script src="//js.honeybadger.io/v0.5/honeybadger.min.js" type="text/javascript" data-apiKey="project api key" data-environment="production" data-revision="git SHA/project version"></script>
```

If you're doing that and still don't have errors reported, can you send me a gist/jsfiddle/etc. which reproduces the issue?
