### ISSUE TITLE
What about lite version?

### ISSUE THREAD

**Issue by a-x-** [honeybadger-io/honeybadger-js#82]
Can you provide API for `https://honeybadger.io/.../notify.gif?error=&file=...&client_id=&secret_key=` requests?

I don't want to include more than 7KiB minified library in some projects.

**Comment by joshuap** [comment]
@a-x- I'm not sure what you're asking, exactly; you could use that URL to make your own lighter version of honeybadge.js. Or did you have something else in mind?

**Comment by a-x-** [comment]
Yep, ok

I'm gonna to write something like this:

```js
window.onerror = function(e){var i = new Image(); i.src="
https://api.honeybadger.io/v1/notices/js.gif
?notice[notifier][name]=honeybadger.js
&notice[notifier][url]=https://github.com/honeybadger-io/honeybadger-js
&notice[notifier][version]=0.4.8
&notice[notifier][language]=javascript
&notice[error][class]=%error.name%
&notice[error][message]=%error.message%
&notice[error][backtrace]=%error.stack%
&notice[request][url]=%location.href%
&notice[request][cgi_data][HTTP_USER_AGENT]=%navigator.userAgent%
&notice[request][cgi_data][HTTP_REFERER]=%document.referrer%
&notice[server][project_root]=%location.host%
&notice[server][environment_name]=production
&api_key=%api_key$
&t=%new Date().getTime()%
";}
```

Can I omit some fields?:
- `notice[notifier][url]`
- `notice[notifier][name]`

**Comment by joshuap** [comment]
Yeah, you should be able to omit those. The required ones are `notice[error]` and `notice[server]`.

**Comment by a-x-** [comment]
Thank you!
And finnaly can you help me with tags?

I tried so:
```
+ '&notice[request][context][tags]=three_d_sec'
+ '&notice[request][context][:tags]=three_d_sec'
```

**Comment by joshuap** [comment]
Try this (I think it should work):

```
+ '&notice[error]['tags'][]=one'
+ '&notice[error]['tags'][]=two'
```

**Comment by a-x-** [comment]
Yay, cool!
