### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'url') when reporting is disabled

### ISSUE THREAD

**Issue by qnighy** [honeybadger-io/honeybadger-js#829]
## What are the steps to reproduce this issue?

1. Initialize Honeybadger with `reportData: false` on a browser.
2. Call `Honeybadger.notify(new Error())`.

## What happens?

`TypeError: Cannot read properties of null (reading 'url')` is thrown.

## What were you expecting to happen?

No error is thrown.

## Any logs, error output, etc?
…

## Any other comments?

This is caused by https://github.com/honeybadger-io/honeybadger-js/blob/v4.0.3/src/browser.ts#L33.

## What versions are you using?
**Operating System:** …
**Package Version:** v4
**Browser Version:** …

**Comment by subzero10** [comment]
Hey @qnighy, thank you for submitting an issue **and** going through the trouble of investigating the source! I will fix this in the next few days.

**Comment by subzero10** [comment]
Hey @qnighy, I just submitted #834 for a fix to this issue.
However, I was only able to reproduce the error by calling `Honeybadger.notify({})`; if I do `Honeybadger.notify(new Error())` I don't get the error.

**Comment by qnighy** [comment]
Thank you for the fix! That is what I want to get although I'm not sure why there is a difference between `{}` and `new Error()`.

**Comment by subzero10** [comment]
Hmm, OK let's test with the new fix and see if you still get it. I will let you know when a new version is released. It should be in the coming days!

**Comment by subzero10** [comment]
Hey @qnighy, can you please try again with `v4.0.4`? Thanks!

**Comment by qnighy** [comment]
It's working now, thanks!

**Comment by subzero10** [comment]
Great! Glad I could help!
