### ISSUE TITLE
Support `Error.cause`

### ISSUE THREAD

**Issue by shalvah** [honeybadger-io/honeybadger-js#847]
[`error.cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) was [recently standardized in JavaScript](https://2ality.com/2021/06/error-cause.html) (but it's been around on some platforms before that).

`error.cause` is useful in nested error situations, such as when we encounter an error while trying to report an error (as recently in #825 ). In such scenarios, `.cause` would be set to the original error, so we have enough information to investigate the issue. Several other languages, like PHP and Ruby support this or something similar.

I'm not sure if we already support it, but we should. "Support" would mean being able to display a "Caused by ..." pointing to the original error + stacktrace. This might be more of a backend issue than a client issue, but will investigate.

**Comment by joshuap** [comment]
We do support it, and I recently created a similar issue with more details that will also be useful here! https://github.com/honeybadger-io/honeybadger-python/issues/111

**Comment by shalvah** [comment]
Nice, thanks!
