### ISSUE TITLE
Using root as assets folder

### ISSUE THREAD

**Issue by rvdsarr** [honeybadger-io/honeybadger-js#878]
Hi guys, 

I am using my root as assets folder (Laravel 8). The webpack extension finds the assets in /js/app.js and /css/app.css.
This however did not work for me, as HoneybadgerSourceMapPlugin.js line 207 checks for ending "/" and adds it if missing. 

So for me that added a double slash. https://example.com//js/app.js which did not work. 

var sep = this.assetsUrl.endsWith('/') ? '' : '/';
var sep = ''; //This fixed it for me.

Maybe there is some other reason why this is happening but this is just for other if they have the same problem.

Roy

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b87q9)

Package Name: @honeybadger-io/webpack

**Comment by subzero10** [comment]
Hey @rvdsarr, I tried to reproduce this by creating a laravel app, but then I saw that the latest version of laravel (v9) does not come with Laravel Mix.

I changed the logic to build the url and then use regex to remove any duplicate slashes (see #886).
I tested the following combinations:
- `assetsUrl = 'https://example.com'` | `sourceFile = '/js/app.js'` => `https://example.com/js/app.js` 
- `assetsUrl = 'https://example.com'` | `sourceFile = 'js/app.js'` => `https://example.com/js/app.js`
- `assetsUrl = 'https://example.com/'` | `sourceFile = '/js/app.js'` => `https://example.com/js/app.js`
- `assetsUrl = 'https://example.com/'` | `sourceFile = 'js/app.js'` => `https://example.com/js/app.js`

I think that should do it, right?

cc @joshuap

**Comment by subzero10** [comment]
> I'm still curious _why_ it's producing duplicate slashes, but removing them seems like a good preemptive step to me.

Same! I'd be able to debug further with a reproducible example, but #886 makes sense to merge.

**Comment by rvdsarr** [comment]
Hi guys, 

Thanks for the quick responds! I can confirm above fix works for me and all seems ok now.

I am using "laravel/framework": "^8.65", at the moment. If you want, I can send you (private) my package and composer files so you can resproduce?
