### ISSUE TITLE
Tags not applied from context

### ISSUE THREAD

**Issue by emwads** [honeybadger-io/honeybadger-js#91]
According to the docs, a key of `tags` in the error context should update the tags applied to the error. https://docs.honeybadger.io/lib/javascript/guides/customizing-error-reports.html#custom-metadata-context 

I've succesfully sent errors with the `tags` key in the context, but it doesn't populate the tags in the error notice page.

**Comment by stympy** [comment]
I have confirmed this bug, and I'm working on a fix.

**Comment by stympy** [comment]
I have deployed a fix for this bug in our API, so you don't need to make any changes to your app.  Errors reported with tags in the context should now work as expected.

**Comment by emwads** [comment]
Thanks!
