### ISSUE TITLE
API should match honeybadger.js

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#925]
This library does not use our [more robust universal honeybadger.js client](https://github.com/honeybadger-io/honeybadger-js) (I'm not sure if we could depend on that project in the future, which would allow us to share more of the features already implemented there—see honeybadger-io/honeybadger-js#926). In any case, it seems like it would be good to use the same APIs that people are already familiar with.

See also: [Client Library Spec](https://www.notion.so/honeybadger/Client-Library-Spec-aa891332f7874196aa0695b6d38dca66)

I looked through the examples for this project and found a few things which should probably match honeybadger.js.

[Configure API:](https://docs.honeybadger.io/lib/javascript/reference/configuration.html#configuration-options)

```js
// honeybadger-react-native
Honeybadger.configure( "API key" )

// honeybadger-js
Honeybadger.configure({ apiKey: "API key" })
```

[Context API:](https://docs.honeybadger.io/lib/javascript/guides/customizing-error-reports.html#adding-context)

```js
// honeybadger-react-native
Honeybadger.resetContext()

// honeybadger-js
Honeybadger.clear()
```

[Notify API:](https://docs.honeybadger.io/lib/javascript/guides/reporting-errors.html#additional-options)

```js
// honeybadger-react-native
Honeybadger.notify(error, additionalData)

// honeybadger-js
Honeybadger.notify(error, { context: additionalData })
```
Note: I assume `additionalData` is added as context, but I'm not sure?

**Comment by subzero10** [comment]
Note: Reminder to update the [README](https://github.com/honeybadger-io/honeybadger-js/tree/master/packages/react-native#configuration) section with this change.

**Comment by BethanyBerkowitz** [comment]
This should be handled by #926 and #932
