### ISSUE TITLE
Errors won't log correctly with Webpack (window.onerror uses ErrorEvent)

### ISSUE THREAD

**Issue by geoffreak** [honeybadger-io/honeybadger-js#93]
@rathboma and I have been trying to figure out this issue to no avail. There's some quirk with this script when using Webpack that changes how the errors get handled.

:+1: The error I expect to see in Chrome without Honeybadger
![](https://snap.sal.tt/ytnr2ime37yur95t3e2hlry2ka1ozx3oaqd.png)

:-1: How things appear in Chrome with Webpack
![](https://snap.sal.tt/ngz3uh85h4a7ws3vhcfwh8vw8y5wbfoz78q.png)

:-1: How things appear in Safari with Webpack
![](https://snap.sal.tt/k1gc4zpjdu3dh4m3ka9qm2hbofh7rmp1s6y.png)

❓ How things appear in Chrome when using the CDN (using an undeployable CORS workaround)
![](https://snap.sal.tt/9twkrm6slug1v1zwz8ftqmaug0fd96qhpgn.png)

Seems like there needs to be some changes made to support `ErrorEvent` properly. I see some logic that sets `preferCatch = false`, but I'm not sure what it's doing. I can say this logic is indeed setting `preferCatch = false` correctly in these incorrect logging cases, so I'm not sure if there's a bug or a design oversight. There doesn't seem to be any logic that checks for the case when `msg` is a `ErrorEvent` in the onerror handler.

**Comment by geoffreak** [comment]
Also of note for Webpack issues, `console.log`s don't work at all now with Webpack. I had to use [this fix](https://github.com/geoffreak/honeybadger-js/commit/a9a5a815dfb5a7b17c14eaa6c0feaf1763c0b6dc) to get around the issue, but I'm not sure this is a good workaround. My fix from before stopped errors from being thrown, but disabled logging.

**Comment by monde** [comment]
@geoffreak re: CORs error - I ran into what I think a similar issue working on our rails webpacker example when running on localhost, see my notes about the webpacker `devtool` setting: https://github.com/honeybadger-io/honeybadger-rails-webpacker-example#notes

**Comment by monde** [comment]
@geoffreak didn't your PR #92  related to issue #88 fix the console issue?

**Comment by geoffreak** [comment]
My PR fixed the console issue from throwing errors, but it still doesn't allow logging as it turns out. Not sure how I missed that.

Actually I figured out that the eval-source-map was causing CORS issues and switched to using an eval-less source map, so I fixed that one. I'm not using any eval anything in these examples. The issue isn't a CORS issue in this case. The problem is `window.onerror` is receiving an `ErrorEvent` object as the first and only parameter when the honeybadgerjs script is included within a build. The code is only handling the function signature with 5 parameters and ends up assigning ErrorEvent to the error's `message` key.

```js
Honeybadger.beforeNotify((error) => {
  if (window.ErrorEvent && error.message instanceof window.ErrorEvent) {
    console.log('error event!', error.message);
  }
  return true;
});
```
![](https://snap.sal.tt/c2yk284c63d5c8s94cla9w36f72xt2zcwgf.png)

**Comment by geoffreak** [comment]
This is what I'm currently using as a workaround for this issue: 

```js
Honeybadger.beforeNotify((error) => {
  // window.onerror ErrorEvent handling due to a bug in honeybadger-js
  if (window.ErrorEvent && error.message instanceof window.ErrorEvent) {
    const errorEvent = error.message;
    if (window.console) { console.error(errorEvent.error); }
    error.message = errorEvent.message;
    error.stack = errorEvent.error.stacktrace || errorEvent.error.stack || undefined;
  // General error logging
  } else if (window.console) {
    console.error(error);
  }
  error.cookies = document.cookie;
  return true;
});
```

**Comment by joshuap** [comment]
@geoffreak interesting. I haven't heard of `window.onerror` being called with just an `ErrorEvent` object. Is that a Webpack thing? According to the API docs, the API for the `window.onerror` handler is clear:

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

I don't think it would be right to modify our handler to work with undocumented edge cases (if that's what this is).

I do notice, however, that the `window.addEventListener('error')` and `element.onerror` both expect a single `ErrorEvent` argument. Is it possible the wires are getting crossed somehow, and the `window.onerror` handler is being called incorrectly?

**Comment by geoffreak** [comment]
I'm not really certain. We're running babel, webpack, and uglify-es, so I suppose that any one of them could be causing the issue when combined with honeybadgerjs.

It really does seem that one of the other types of error handlers is being used, but the logic for window.onerror is being called somehow. 

I can't help but wonder if there are many more quirks with this library being used with webpack. Webpack is a commonly used tool for building assets and it really seems that honeybadgerjs can't play nice with it. 

Are there any plans to add testing against webpack and possibly refactor a few things to make sure these issues are eliminated properly? I really can't push patches to fix the symptoms as I don't understand the logic behind the library's implementation nor do I fully understand what webpack layering between libraries and the browser that would cause it to behave so differently. 

We don't have any such issues with other libraries we are using, so I can only assume that others have figured out what the quirks are.

**Comment by joshuap** [comment]
@geoffreak we have lots of customers using honeybager.js with webpack, and haven't had any other reports of problems. Let us know if you find the source of the incorrect `window.onerror` API call (closing this, as it doesn't appear to be an issue with our library).
