### ISSUE TITLE
Cannot read properties of undefined (reading 'breadcrumbs')

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-js#937]
A user reports that they have an Express backend that is crashing with the following error:

> ```
> /usr/src/app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:871
>         var breadcrumbs = store.breadcrumbs;
>                                 ^
> TypeError: Cannot read properties of undefined (reading 'breadcrumbs')
>     at Honeybadger.Client.addBreadcrumb (/usr/src/app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:871:33)
>     at Honeybadger.Client.notify (/usr/src/app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:727:14)
>     at process.honeybadgerUncaughtExceptionListener (/usr/src/app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:1151:28)
>     at process.emit (node:events:525:35)
>     at process.emit (node:domain:489:12)
>     at process._fatalException (node:internal/process/execution:149:25)
> ```
> 
> Our honeybadger file:
> 
> ```js
> const Honeybadger = require('@honeybadger-io/js');
> 
> if (process.env.NODE_ENV !== 'local') {
>   Honeybadger.configure({
>     apiKey: process.env.HONEYBADGER_API_KEY,
>     environment: process.env.NODE_ENV,
>     tags: 'backend'
>   });
>   console.info('🍯 Honeybadger initiated 🐝');
> } else {
>   console.info('🍯 Honeybadger not initiated ❌');
> }
> 
> module.exports = Honeybadger;
> ```
> 
> We're using express in our backend, here's our server index.js file:
> 
> ```
> ... // imports
> const { honey_badger } = require('./services/honeybadger');
> ... // before any routes
> app.use(honey_badger.requestHandler);
> ... // routes between these two
> app.use(honey_badger.errorHandler);
> ... // more code here
> ```

cc @subzero10 @shalvah 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e4zvl)

**Comment by subzero10** [comment]
Which version are they using? This should already be fixed with #905.

**Comment by joshuap** [comment]
> Which version are they using? This should already be fixed with #905 ( >= v4.6.0 ).

I emailed to ask, will report back here.
