### ISSUE TITLE
`uncaughtException` handler not working as expected with latest release

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#960]
While manually testing `v4.7.4` I noticed that for `uncaughtException`, we register 2 listeners (at least that's how it appears to be so):
- `domainUncaughtExceptionClear`
- `honeybadgerUncaughtExceptionListener`

Moreover, the Honeybadger [instance sets `fatallyLogAndExit` as the `afterUncaught` handler](https://github.com/honeybadger-io/honeybadger-js/blob/master/packages/js/src/server.ts#L41), which exits the process regardless the number of listeners registered.

I would like to:
- investigate where this `domainUncaughtExceptionClear` listener comes from 
- remove the `afterUncaught: fatallyLogAndExit` assignment
- and spend some time to see if I can write some tests for our logic in these listeners.

**Comment by BethanyBerkowitz** [comment]
One interesting option here - the [`uncaughtExceptionMonitor` event](https://nodejs.org/api/process.html#event-uncaughtexceptionmonitor) was added in Node 12/13 (so it should be available in all of our currently supported node versions). It doesn't override the default behavior, so it seems like our logic for when to exit vs not could be removed if we used this event. However, we'd want to do really thorough testing before making a change like this since catching the uncaught exceptions is such an important baseline feature.

**Comment by BethanyBerkowitz** [comment]
The listener `domainUncaughtExceptionClear` is apparently something attached [by node itself](https://github.com/nodejs/node/blob/6432060c7ce1670467c230d2c0c925465dd311f8/lib/domain.js#L207). 

It's confusing that this listener is still attached, considering that [domains appear to have been deprecated years and years ago](https://nodejs.org/api/domain.html). 

@subzero10 do you remember where you saw this listener popping up? Was it in one of our test projects? I'm curious when and why it is still attached if domains are deprecated.

**Comment by subzero10** [comment]
> One interesting option here - the [uncaughtExceptionMonitor event](https://nodejs.org/api/process.html#event-uncaughtexceptionmonitor) was added in Node 12/13 (so it should be available in all of our currently supported node versions). It doesn't override the default behavior, so it seems like our logic for when to exit vs not could be removed if we used this event. However, we'd want to do really thorough testing before making a change like this since catching the uncaught exceptions is such an important baseline feature.
> 
> [edit] I also haven't yet looked into how this works with potentially async code -- we don't want the process to shut down before the notification is sent off.

I would vote to go for this. We [considered it again](https://github.com/honeybadger-io/honeybadger-js/pull/950#issuecomment-1327808719) some time ago, we just didn't go for it because it was added in the latest versions of Node 12/13, which meant not a lot of support even for those on Node 12/13.
However, now that we've officially dropped support for these versions we can go for the `uncaughtExceptionMonitor` event, which is a lot simpler to implement and more suited to our needs.
**Your last point is crucial though, can you see whether async code is supported?**

> The listener domainUncaughtExceptionClear is apparently something attached [by node itself](https://github.com/nodejs/node/blob/6432060c7ce1670467c230d2c0c925465dd311f8/lib/domain.js#L207).
>
> It's confusing that this listener is still attached, considering that [domains appear to have been deprecated years and years ago](https://nodejs.org/api/domain.html).
> 
> @subzero10 do you remember where you saw this listener popping up? Was it in one of our test projects? I'm curious when and why it is still attached if domains are deprecated.

I do! We actually use domains, because even though they have been deprecated for years, we haven't found a reliable way to replicate their functionality.  You can read more about this [here](https://github.com/honeybadger-io/honeybadger-js/blob/9899f6ed8e9b4f4d06adb984670b657548cef306/packages/js/src/server.ts#L109) and there is mention of domains in #711 as well.

**Comment by BethanyBerkowitz** [comment]
Ok, so I did some investigation of `uncaughtExceptionMonitor` and I'm disappointed to report that I don't think it's going to solve our problems. **TLDR: using `uncaughtExceptionMonitor`, the process exits before the notice makes it to Honeybadger.** 

Here's the testing I did in detail, with notes on the results inline:
```javascript
import Honeybadger from '@honeybadger-io/js'

// USAGE: node index.mjs your_api_key_here notifyAsync reject
const apiKey = process.argv[2]
const method = process.argv[3] || 'notify' // control, notify, or notifyAsync
const errorType = process.argv[4] || 'throw' // throw or reject

Honeybadger.configure({
  apiKey, 
  enableUncaught: false, 
  enableUnhandledRejection: false,
  reportData: true,
})

// control
// 
// This is a simplified version of what we currently do for comparison
// The error makes it to HB correctly
// Example output: 
//   uncaughtException handler triggered with err: This error was thrown synchronously and not caught
//   origin: uncaughtException
//   notify was called
//   Reported to HB, about to exit
if (method === 'control') {
  process.on('uncaughtException', (err, origin) => {
    console.log('uncaughtException handler triggered with err:', err.message) 
    console.log('origin:', origin) 
    Honeybadger.notify(err, {
      afterNotify: () => {
        console.log('Reported to HB, about to exit') 
        process.exit(1)
       }
    }) 
    console.log('notify was called') 
  })
}


// notify
//
// This an attempt to use the uncaughtExceptionMonitor event with notify()
// It doesn't work -- the process exits before the notice goes to HB
// Example output: 
//   uncaughtExceptionMonitor handler triggered with err: This error was thrown synchronously and not caught
//   origin: uncaughtException
//   notify was called
if (method === 'notify') {
  process.on('uncaughtExceptionMonitor', (err, origin) => {
    console.log('uncaughtExceptionMonitor handler triggered with err:', err.message)
    console.log('origin:', origin) 
    // Error never makes it to HB
    Honeybadger.notify(err, {
      afterNotify: () => {
        console.log('Reported to HB') // Never see this
      }
    })
    console.log('notify was called')
  })
}


// notifyAsync
// 
// This an attempt to use the uncaughtExceptionMonitor event with notifyAsync()
// It doesn't work -- the process exits before the notice goes to HB
// Example output: 
//   async uncaughtExceptionMonitor handler triggered with err: This error was thrown synchronously and not caught
//   origin: uncaughtException
if (method === 'notifyAsync') {
  process.on('uncaughtExceptionMonitor', async (err, origin) => {
    console.log('async uncaughtExceptionMonitor handler triggered with err:', err.message) 
    console.log('origin:', origin) 
    await Honeybadger.notifyAsync(err) // Error never makes it to HB
    console.log('notifyAsync completed') // Never see this
  })
}


// If you throw an error at the top level by just doing 
// throw new Error(), the origin will always be unhandledRejection
// Because rejection happens during the command line entry point's ES module static loading phase
// (according to the docs https://nodejs.org/api/process.html#event-uncaughtexceptionmonitor)
// By allowing the module to load without issue before throwing, we see the uncaughtException origin
function throwError() {
  throw new Error('This error was thrown synchronously and not caught')
}
if (errorType === 'throw') {
  setTimeout(throwError, 500)
}

// This will have origin unhandledRejection
function rejectPromise() {
  Promise.reject('This promise rejection is unhandled')
}
if (errorType === 'reject') {
  setTimeout(rejectPromise, 500)
}
```

I guess node intended only synchronous code to be used within `uncaughtExceptionMonitor`. After doing the testing above, I noticed that [their docs](https://nodejs.org/api/process.html#event-uncaughtexceptionmonitor) actually imply this by making the example code in the handler `MyMonitoringTool.logSync(err, origin)` 🤦‍♀️. I guess this event could be used if you just wanted to write to a log file on your own server that you're running node on, but otherwise it seems not so useful.

**Comment by BethanyBerkowitz** [comment]
I believe https://github.com/honeybadger-io/honeybadger-js/pull/1161 handled everything in this issue. 

I added these two issues based on what was found while working on this one:
https://github.com/honeybadger-io/honeybadger-js/issues/1163
https://github.com/honeybadger-io/honeybadger-js/issues/1165
