### ISSUE TITLE
Unrelated errors getting grouped together

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#979]
Hello,

We are currently using honeybadger with a node/express application, and continue to see an issue that we're not sure of the best way to solve. Unrelated errors get grouped under a single error item within honeybadger, which is obscuring some errors, and just in general gets them mixed up. Here's one example: https://app.honeybadger.io/projects/103978/faults/91269777

And a screenshot of what it looks like when you click through:
Screen Shot 2022-12-07 at 10.34.16 AM.png

Note that these are two totally different errors from different parts of the application. Can you help us to understand why this would happen, or if there are any steps we can take on our side to prevent this when sending errors to honeybadger?

Thank you!
Eric

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fk0pt)

**Comment by subzero10** [comment]
Update on this:
- I went through the notice in example and I realised that these notices were not reported with a stack trace (i.e. notice was reported with a message:`hb.notify('Error creating index for model "adChoices":')`)
- When this happens, we [generate a stack trace internally](https://github.com/honeybadger-io/honeybadger-js/blob/a5fd0e973b02bf075afb85752ce71839b216ae44/packages/core/src/client.ts#L317) and then we just remove the first 2 frames of the stack. **This is what broke.**
- The 2 frames made the assumption that only 2 functions calls would happen inside our js client. This has changed with the introduction of `notifyAsync` and the extraction to a core js package.

I am working on a way to filter out the first frames that are pointing to the honeybadger source code, without specifying a hardcoded number. This way, we will have a more future-proof solution.
For example, we could loop through the stack and remove the frames that have source file from `'@honeybadger-io'`:
```
/**
 * If {@link generateStackTrace} is used, we want to exclude frames that come from
 * honeybadger's source code.
 */
function calculateBacktraceShift(backtrace: BacktraceFrame[]) {
  let shift = 0
  for (const line of backtrace) {
    if (line.file.indexOf('@honeybadger-io') > -1) {
      shift++
    }
    else {
      break
    }
  }

  return shift
}
```

I will have a PR for review soon (probably tomorrow).

**Comment by subzero10** [comment]
OK, PR #982 is ready with a fix, but I'm pretty sure it won't resolve the user's issue.

Upon further inspection I noticed the following:
- Even with honeybadger's source code removed, the stack trace will still be almost identical. I'm looking at last 2 notices of the above fault (91269777) - see image below with a diff checker
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/5813382/208135838-3e96140b-df15-45a2-aa38-85f35ede4060.png">

They are using winston with a Honeybadger transport (should we dive into this??) and winston is creating a stack trace coming from a separate stream. I don't think there's anything we can do on our side to get better information.

Since these two notices have different messages, why would they end up in the same group? Is message not considered at all in grouping? Shouldn't it be considered (even with a lower weight), especially when the stack trace is almost identical? [It seems that it's not](https://docs.honeybadger.io/guides/errors/#error-grouping). Can we consider changing this behavior? I know that [Sentry](https://docs.sentry.io/product/data-management-settings/event-grouping/) uses it in their algorithm.

Finally, we can suggest to the user that in the cases where they are not reporting an error, they can leverage [custom footprints](https://docs.honeybadger.io/lib/javascript/guides/customizing-error-grouping/#creating-your-own-fingerprints). I think this is their best option for success considering that the stack trace is not helpful, even after excluding honeybadger's source code.

Tagging many people to get your thoughts :) @BethanyBerkowitz @stympy @joshuap @shalvah

**Comment by shalvah** [comment]
I agree. I think the message should be included in the fingerprint. If not the whole message, at least some similarity level. In strongly-typed environments, it might make sense to group on class alone. But in weaker languages like JS, it's common to see `throw new Error('...')` a bunch of places.

The other day (while working on the SIdekiq upgrade), and I had a line `raise RuntimeError, 'with Sidekiq 7'`. It was pretty annoying that I couldn't simply change the message to see it show up as a separate error. I had to change the error class too. Eventually you run out of error classes...

**Comment by BethanyBerkowitz** [comment]
Agreed that in javascript, it's pretty common to just throw an error with a useful message but not a unique class. As a JS dev, I would probably expect my errors to be grouped by message. You can create custom error classes, but I don't think most people do so very often.

**Comment by subzero10** [comment]
> Agreed that in javascript, it's pretty common to just throw an error with a useful message but not a unique class. As a JS dev, I would probably expect my errors to be grouped by message. You can create custom error classes, but I don't think most people do so very often.

Usually you should be covered from the stack trace (it would be different - so different error), but as we've seen, it is possible to get almost identical stack traces with different messages.

**Comment by stympy** [comment]
The server-side fingerprinting for javascript errors does not look at the message. I would be fine with changing this to include the message. It may be prudent to make that change as part of a major version bump.

**Comment by shalvah** [comment]
> error messages might not be identical and yet still be related (eg `Failed to create user bethany@hb.io` and `Failed to create user pan@hb.io`). So it's not a trivial problem

That's actually less complicated than it seems @BethanyBerkowitz . There are algorithms to calculate the similarity of two strings (such as PHP's [`levenshtein()` function](https://www.php.net/manual/en/function.levenshtein.php), and there are heuristics we can use to improve the accuracy (replacing tokens like emails, UUIDS, and probably numbers).

I personally think it's worth including the normalized message in the server-side fingerprint by default, but I guess that might be too big a change.

**Comment by stympy** [comment]
As a precautionary tale, there are customers who choose to include the message in fingerprint generation _without_ normalizing them in any way, resulting in broken grouping and hundreds of unwanted notifications. It may be more complicated than you think, @shalvah. 😁

**Comment by subzero10** [comment]
> The server-side fingerprinting for javascript errors does not look at the message. I would be fine with changing this to include the message. It may be prudent to make that change as part of a major version bump.

I'm all for the "message" inclusion in error grouping. Can you elaborate on how this would be part of a major version bump since the change will be on the backend?
Are you suggesting that we make this an feature that can be enabled/disabled from the client-side? And with the major version bump to enable it by default?

> That's actually less complicated than it seems @BethanyBerkowitz . There are algorithms to calculate the similarity of two strings (such as PHP's [levenshtein() function](https://www.php.net/manual/en/function.levenshtein.php)), and there are normalizations we can apply to improve the accuracy (replacing tokens like emails, UUIDS, and probably numbers).

> I personally feel like it's worth including the normalized message in the server-side fingerprint by default, but I guess that might be too big a change.

> As a precautionary tale, there are customers who choose to include the message in fingerprint generation without normalization, resulting in broken grouping and hundreds of unwanted notifications. It may be more complicated than you think, @shalvah. 😁

Here's my experience with competitors:
- it does not look like it they normalise messages,
- instead they add a weight to the different rules (message, stack trace, exception) and compute the group based on them. So, even if message is added by default to issue grouping, it won't have the same impact as the stack trace or the exception type. I didn't think this through yet, but I agree it can get complex. Though, I know that it doesn't have to be perfect, users can still leverage custom fingerprints for the cases it won't work. We just need to be careful so that those cases are a small fraction of the total no of notices.

**Comment by stympy** [comment]
> I'm all for the "message" inclusion in error grouping. Can you elaborate on how this would be part of a major version bump since the change will be on the backend?

We want to minimize disruption to the current behavior customers are experiencing, and if we change how the fingerprinting is done on the server-side, that could cause grouping (and notifications) to change unexpectedly for existing customers. We can tie the server-side fingerprinting algorithm to the version of the client library that is being used, so if we make the change part of a major version bump, then customers can be advised of the change in the changelog (which they are more likely to check with a major version change than a minor one).

> Are you suggesting that we make this a feature that can be enabled/disabled from the client-side? And with the major version bump to enable it by default?

I wasn't suggesting that, but that's an interesting idea. 😁 You could even take it a step further and provide multiple, client-side-selectable fingerprint algorithms. 🤔

**Comment by joshuap** [comment]
Adding the message to grouping *is* a feature people have requested in the past, and I think we've suggested they use the custom client-side fingerprint option to achieve it. A problem with calculating fingerprints client side is that source maps may not be applied. We've also considered adding some server-side feature that would allow for more custom grouping.

It would be sort of interesting if you could send a client-side fingerprint that would get _added_ to the default server-side fingerprint rather than replace it.

**Comment by subzero10** [comment]
> We can tie the server-side fingerprinting algorithm to the version of the client library that is being used, so if we make the change part of a major version bump, then customers can be advised of the change in the changelog (which they are more likely to check with a major version change than a minor one).

Oh, that's a good idea! The major version bump makes more sense now!

> It would be sort of interesting if you could send a client-side fingerprint that would get added to the default server-side fingerprint rather than replace it (e.g. basically function like change the class name does).

Yeah, that'd be great. I have used this feature specifically with other products. My use case was "I know that the default fingerprinting algo is good enough for most cases, I just want to add to it to cover my _special_ cases". We could do that by supporting some variable mechanism, like:
```
// {{ honeybadger_default }} is something that the backend will calculate
fingerprint: `{{ honeybadger_default }} {err ? err.message : ''}`
```
In this case, the default fingerprint would be used, plus the error message (if available). The limitation with this is that `err.message` will influence default fingerprint result for _every_ notice. Then again, you could send this config only in specific notices.

**Comment by joshuap** [comment]
> ```
> // {{ honeybadger_default }} is something that the backend will calculate
> fingerprint: `{{ honeybadger_default }} {err ? err.message : ''}`
> ```
> In this case, the default fingerprint would be used, plus the error message (if available). The limitation with this is that `err.message` will influence default fingerprint result for _every_ notice. Then again, you could send this config only in specific notices.

Good idea! One thing to note, if you go this direction: make sure the `honeybadger_default` token syntax makes sense for all languages. In the past we've used something closer to `[honeybadger_default]` for special tokens ([example](https://docs.honeybadger.io/guides/integrations/#custom-formatters)).
