### ISSUE TITLE
Using `onerror` with Honeybadger factories doesn't work

### ISSUE THREAD

**Issue by frewsxcv** [honeybadger-io/honeybadger-js#98]
```javascript
const honeybadger1 = Honeybadger.factory({ onerror: false });
const honeybadger2 = Honeybadger.factory({ onerror: true });
```

If an exception occurs, my understanding is that it will only be caught with the `honeybadger1` config, so the error will _not_ be reported to Honeybadger. Relevant code:

- https://github.com/honeybadger-io/honeybadger-js/blob/5daf556f4c8be605ebcc9c7d277070fc67f85924/honeybadger.js#L547
- https://github.com/honeybadger-io/honeybadger-js/blob/5daf556f4c8be605ebcc9c7d277070fc67f85924/honeybadger.js#L494

It seems either:

- The `Honeybadger.factory` documentation should call this out
- OR the `onerror` handler should (somehow) look through all configs and check if any of them have `onerror: true`

**Comment by joshuap** [comment]
@frewsxcv I actually think we may not want to install the `onerror` handler at all when calling `Honeybadger.factory` directly. How are you importing `Honeybadger`? The way the module loader is built, it should create a singleton instance of factory which is what the `onerror` handler should always be attached to. i.e.:

```js
const Honeybadger = require('honeybadger-js')
Honeybadger // This should be a factory instance which the `onerror` handler attached
const honeybadger1 = Honeybadger.factory(); // This should never have `onerror` attached
const honeybadger2 = Honeybadger.factory(); // ditto
```

**Comment by frewsxcv** [comment]
> I actually think we may not want to install the `onerror` handler at all when calling `Honeybadger.factory` directly.

If you end up doing this, I think it'd be good to call this out in the `Honeybadger.factory` documentation.

**Comment by joshuap** [comment]
I called out this behavior in the docs here: https://docs.honeybadger.io/lib/javascript/guides/working-with-multiple-clients.html
