### ISSUE TITLE
Webpack plugin inappropriately logs that there are no files to upload

### ISSUE THREAD

**Issue by BethanyBerkowitz** [honeybadger-io/honeybadger-js#980]
## What are the steps to reproduce this issue?
1. I forked https://github.com/honeybadger-io/nextjs-with-honeybadger and deployed it to vercel
2. Check the logs in vercel and I see both "no assets" error and logging that suggests the sourcemaps were correctly uploaded

## What happens?
<img width="1006" alt="Screen Shot 2022-12-12 at 10 17 34 AM" src="https://user-images.githubusercontent.com/16493493/207082498-ba3cb5d5-e62f-4d48-8275-ede9330f2b51.png">

It's logging both that there are no assets to upload, and that it successfully uploaded sourcemaps. One of these logs is wrong. 

## What were you expecting to happen?
Either there are no assets, or there are assets uploaded, not both!

## Any logs, error output, etc?
See above

**Comment by subzero10** [comment]
I'm keen to know more about this.
Here's an [issue](https://github.com/honeybadger-io/honeybadger-js/issues/880#issuecomment-1245718799) where I looked into a little bit. Basically, I came to realize that next.js runs the "build" command multiple times simultaneously (for different purposes), and in some of those cases, it doesn't generate source maps.

**Comment by BethanyBerkowitz** [comment]
> I'm keen to know more about this. Here's an [issue](https://github.com/honeybadger-io/honeybadger-js/issues/880#issuecomment-1245718799) where I looked into a little bit. Basically, I came to realize that next.js runs the "build" command multiple times simultaneously (for different purposes), and in some of those cases, it doesn't generate source maps.

Yeah, I looked into this a bit on Monday and found the same thing. At first I was wondering if it just "emits" assets several times, causing the `afterEmit` hook to fire multiple times for one build. However, I checked the `done` hook and that one gets fired multiple times too, so it's definitely running the "build" command more than once. 

So yes, this logging is pretty confusing for the user, but I don't know that we can do much about it.

**Comment by BethanyBerkowitz** [comment]
Since we now understand and have documented the cause of this and there's not an obvious way to fix it, I'm inclined to close this for now.
