### ISSUE TITLE
Honeybadger v.0.5.x doesn't seem to load due to incorrect module packaging

### ISSUE THREAD

**Issue by aeschylus** [honeybadger-io/honeybadger-js#99]
This [documentation](https://docs.honeybadger.io/lib/javascript/integration/browser.html) indicates I should be able to load the honeybadger-js reporting scripts over CDN, and feed it the appropriate api keys and so on through the tag's data attributes. However, when adding this as described (though with the erroneous url indicated in the documentation corrected), the script comes in, but is malformed. upon loading, it produces the error:

<img width="437" alt="screenshot 2018-12-03 at 2 02 45 pm" src="https://user-images.githubusercontent.com/145874/49404381-248dc200-f704-11e8-85d7-6aeb96cd478a.png"> 

(See almond README: incorrect module build, no module name)  

This [apparently](https://github.com/requirejs/almond/blob/master/README.md#incorrect-module-build-no-module-name) results from the module being anonymous. Perhaps there are other settings needed in the build to allow anonymous packaging in the browser environment.

**Comment by joshuap** [comment]
@aeschylus which link in the documentation is erroneous? We used the [UMD project](https://github.com/umdjs/umd) to define our module loader. Maybe there is some info about this there? I am not familiar with almond.

**Comment by joshuap** [comment]
I added an example of using honeybadger.js w/ almond here:

https://github.com/honeybadger-io/honeybadger-js/tree/master/examples/almond

Closing this out, since I'm not seeing any issues with building the module.
