### ISSUE TITLE
[Vue warn]: Property ("_isVue" | "constructor") was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by ordago** [honeybadger-io/honeybadger-js#996]
I'm using honeybadger with Laravel, Inertia and Vue3.

Honeybadger seems to be accessing a Vue2 deprecated property.

I found the equivalent issue in Sentry while searching the error
https://github.com/getsentry/sentry-javascript/issues/4170

And the PR that fixed it:
https://github.com/getsentry/sentry-javascript/pull/4461/files

## What are the steps to reproduce this issue?
1. The error happened when calling `includes` on `null` in a computed property.

## What happens?
Some errors but not others make it so honeybadger throws its own error. 
`[Vue warn]: Property "_isVue" was accessed during render but is not defined on instance.`

## What were you expecting to happen?
…

## Any logs, error output, etc?
Following the stacktrace in the browser points to this line:
`Function.prototype.apply.call(original, _window.console, arguments);`

## Any other comments?

Here are the places where it's used:

https://github.com/honeybadger-io/honeybadger-js/blob/317220310f07edd18283214fe8901cab31218416/packages/vue/src/vue-debug.js#L17

https://github.com/honeybadger-io/honeybadger-js/blob/317220310f07edd18283214fe8901cab31218416/packages/vue/src/vue-debug.js#L44

## What versions are you using?
**Operating System:** Windows 10
**Package Name:**  @honeybadger-io/vue  
**Package Version:** 4.8.2
**Browser Version:** Chrome

**Comment by subzero10** [comment]
Hello @ordago,

Thank you for reporting this with all the detailed information. We'll work on it soon.

**Comment by subzero10** [comment]
Hey @ordago, we just published [@honeybadger-io/vue@4.9.1](https://www.npmjs.com/package/@honeybadger-io/vue) that should fix this!

**Comment by ordago** [comment]
Hi @subzero10!, I've updated to the latest version and now instead of `_isVue` it says `constructor`.

`[Vue warn]: Property "constructor" was accessed during render but is not defined on instance. `

Stacktrace points to the same line:

`Function.prototype.apply.call(original, _window.console, arguments);`

`constructor` seems to be used near where the _isVue was:

https://github.com/honeybadger-io/honeybadger-js/blob/7766fbe10592d27c7e07c4432b4bdef2f2b03be9/packages/vue/src/vue-debug.js#L51-L58

The warning appears several times on the console. All pointing to the same line.

![image](https://user-images.githubusercontent.com/6376814/212477498-7937505a-997c-4f58-a906-708f96c4f595.png)

If I edit to make it check for existence, it throws it only once.

`if ((last?.constructor && vm?.constructor) && last.constructor === vm.constructor) {`

I've tried to make a minimal reproduction, but I haven't managed to make it throw the same error.

**Comment by subzero10** [comment]
Hey @ordago, thanks for trying this out so promptly!

To be honest, I got the constructor warning my self as well, but I wasn't sure if it was related to the example project I was working on or if indeed a more general issue.
This line of code seems to be in the [sentry package](https://github.com/getsentry/sentry-javascript/blob/master/packages/vue/src/components.ts#L54) as well, so I'm wondering if this warning appears on their package as well 🤔 .

Thank you for the suggested improvement, I will see if I can make that go away entirely.

**Comment by subzero10** [comment]
Hey @ordago, I just published `v4.9.3`.

It seems that we get this warning from Vue 3's special `Proxy` wrappers and if we check any property that does not exist on the `vm` it raises the warning. I didn't find a reliable way to check for _recursive components_ so I decided to disable this block of code for Vue 3. I think it's fine without it, as it doesn't appear to be a very common scenario.

**Comment by ordago** [comment]
Hi @subzero10, I triggered the original error with the new version and now the console only shows my error. Thanks!

**Comment by subzero10** [comment]
@ordago Awesome! Thank you for using Honeybadger!
